BEGIN;
INSERT INTO l_accessibilite_type VALUES ('Restreint', 'Verrouillee', '');
INSERT INTO l_accessibilite_type VALUES ('Libre', 'Non verrouillée', '');
INSERT INTO l_adress_etat VALUES ('EXI', 'EXISTANTE', '');
INSERT INTO l_adress_etat VALUES ('CRE', 'A CREER', '');
INSERT INTO l_adress_etat VALUES ('ASU', 'A SUPPRIMER', '');
INSERT INTO l_adress_etat VALUES ('SUP', 'SUPPRIMEE', '');
INSERT INTO l_adress_type VALUES ('R', 'RUE', '');
INSERT INTO l_adress_type VALUES ('AV', 'AVENUE', '');
INSERT INTO l_adress_type VALUES ('IMP', 'IMPASSE', '');
INSERT INTO l_adress_type VALUES ('CHE', 'CHEMIN', '');
INSERT INTO l_adress_type VALUES ('BD', 'BOULEVARD', '');
INSERT INTO l_adress_type VALUES ('RTE', 'ROUTE', '');
INSERT INTO l_adress_type VALUES ('LOT', 'LOTISSEMENT', '');
INSERT INTO l_adress_type VALUES ('CH', 'CHAUSSEE', '');
INSERT INTO l_adress_type VALUES ('VOIE', 'VOIE', '');
INSERT INTO l_adress_type VALUES ('COURS', 'COURS', '');
INSERT INTO l_adress_type VALUES ('ALL', 'ALLEE', '');
INSERT INTO l_adress_type VALUES ('CLOS', 'CLOS', '');
INSERT INTO l_adress_type VALUES ('MTE', 'MONTEE', '');
INSERT INTO l_adress_type VALUES ('HAM', 'HAMEAU', '');
INSERT INTO l_adress_type VALUES ('PL', 'PLACE', '');
INSERT INTO l_adress_type VALUES ('TRA', 'TRAVERSEE', '');
INSERT INTO l_adress_type VALUES ('PAS', 'PASSAGE', '');
INSERT INTO l_adress_type VALUES ('GAL', 'GALERIE', '');
INSERT INTO l_adress_type VALUES ('VIA', 'VIA', '');
INSERT INTO l_artere_implantation_type VALUES ('0', 'AERIEN ORANGE', '');
INSERT INTO l_artere_implantation_type VALUES ('1', 'AERIEN EDF', '');
INSERT INTO l_artere_implantation_type VALUES ('2', 'FACADE', '');
INSERT INTO l_artere_implantation_type VALUES ('3', 'IMMEUBLE', '');
INSERT INTO l_artere_implantation_type VALUES ('4', 'PLEINE TERRE', '');
INSERT INTO l_artere_implantation_type VALUES ('5', 'CANIVEAU', '');
INSERT INTO l_artere_implantation_type VALUES ('6', 'GALERIE', '');
INSERT INTO l_artere_implantation_type VALUES ('7', 'CONDUITE', '');
INSERT INTO l_artere_implantation_type VALUES ('8', 'EGOUT', '');
INSERT INTO l_artere_nature VALUES ('ASS', 'ASSAINISSEMENT', '');
INSERT INTO l_artere_nature VALUES ('EAU', 'EAU', '');
INSERT INTO l_artere_nature VALUES ('ELE', 'ELECTRICITÉ', '');
INSERT INTO l_artere_nature VALUES ('GAZ', 'GAZ', '');
INSERT INTO l_artere_nature VALUES ('NC', 'NON COMMUNIQUÉ', '');
INSERT INTO l_artere_nature VALUES ('TEL', 'TÉLÉCOM', '');
INSERT INTO l_artere_nature VALUES ('HTZ', 'HERZIEN', 'Faisceau hertzien. ');
INSERT INTO l_artere_type VALUES ('CO', 'COLLECTE', 'Liaison entre les PM');
INSERT INTO l_artere_type VALUES ('TR', 'TRANSPORT', '> 144Fo');
INSERT INTO l_artere_type VALUES ('DI', 'DISTRIBUTION', '<= 144Fo');
INSERT INTO l_artere_type VALUES ('AD', 'ADDUCTION', 'Entre le client et la distribution');
INSERT INTO l_artere_type VALUES ('BM', 'BOUCLE METROPOLITAINE', '');
INSERT INTO l_artere_type VALUES ('LH', 'LONGUE DISTANCE (LONG HAUL)', '');
INSERT INTO l_baie_type VALUES ('BAIE', 'BAIE', '');
INSERT INTO l_baie_type VALUES ('FERME', 'FERME', '');
INSERT INTO l_bp_localisation VALUES ('SITE', 'SITE', '');
INSERT INTO l_bp_localisation VALUES ('AERIEN', 'AUTRE AERIEN', '');
INSERT INTO l_bp_localisation VALUES ('CHAMBRE', 'CHAMBRE', '');
INSERT INTO l_bp_racco VALUES ('CLI001', '', '');
INSERT INTO l_bp_racco VALUES ('CLI002', 'CLIENT INJOIGNABLE IMPOSSIBLE DE PRENDRE RDV', '');
INSERT INTO l_bp_racco VALUES ('CLI003', '', '');
INSERT INTO l_bp_racco VALUES ('CLI004', '', '');
INSERT INTO l_bp_racco VALUES ('CLI005', 'CLIENT REFUS CLIENT', '');
INSERT INTO l_bp_racco VALUES ('CLI006', 'CLIENT REFUS GESTIONNAIRE D IMMEUBLES', '');
INSERT INTO l_bp_racco VALUES ('CLI007', 'CLIENT ABSENCE CLIENT LORS DE L INTERVENTION', '');
INSERT INTO l_bp_racco VALUES ('ADR001', '', '');
INSERT INTO l_bp_racco VALUES ('ADR002', '', '');
INSERT INTO l_bp_racco VALUES ('ADR003', '', '');
INSERT INTO l_bp_racco VALUES ('ADR004', '', '');
INSERT INTO l_bp_racco VALUES ('ADR005', '', '');
INSERT INTO l_bp_racco VALUES ('ADR006', '', '');
INSERT INTO l_bp_racco VALUES ('IMP001', '', '');
INSERT INTO l_bp_racco VALUES ('IMP002', 'PB OU PM SATURE', '');
INSERT INTO l_bp_racco VALUES ('IMP003', '', '');
INSERT INTO l_bp_racco VALUES ('IMP004', 'COMMANDE IMPOSSIBLE :  IDENTIFIANT INTERNE OC INCONNUE', '');
INSERT INTO l_bp_racco VALUES ('IMP005', 'FORMAT ERRONE', '');
INSERT INTO l_bp_racco VALUES ('IMP006', 'CHAMPS OBLIGATOIRES MANQUANTS', '');
INSERT INTO l_bp_racco VALUES ('INTER001', 'HL OI : HOTLINE OI INJOIGNABLE', '');
INSERT INTO l_bp_racco VALUES ('INTER002', 'ABSENCE DE CONTINUITE OPTIQUE', '');
INSERT INTO l_bp_racco VALUES ('INTER003', 'AFFAIBLISSEMENT TROP IMPORTANT', '');
INSERT INTO l_bp_racco VALUES ('AUT001', 'AUTRE MOTIF : COMMENTAIRES LIBRES', '');
INSERT INTO l_bp_racco VALUES ('RDV01', 'NOMBRE DE MODIFICATIONS MAX DEPASSE', '');
INSERT INTO l_bp_racco VALUES ('RDV02', '', '');
INSERT INTO l_bp_racco VALUES ('RDV03', 'COMMANDE GELEE', '');
INSERT INTO l_bp_racco VALUES ('RACOK', 'PRISE RACCORDEE', '');
INSERT INTO l_bp_type VALUES ('BPE', 'BOITIER PROTECTION EPISSURE', '');
INSERT INTO l_bp_type VALUES ('PTO', 'PTO', '');
INSERT INTO l_cable_type VALUES ('CABLE', 'CABLE', '');
INSERT INTO l_cable_type VALUES ('JARRETIERE', 'JARRETIERE', '');
INSERT INTO l_cassette_type VALUES ('P', 'PLATEAU DE LOVAGE BPE', '');
INSERT INTO l_cassette_type VALUES ('E', 'EPISSURE', '');
INSERT INTO l_cassette_type VALUES ('S', 'SPLITTER', '');
INSERT INTO l_cassette_type VALUES ('C', 'CONNECTEUR', '');
INSERT INTO l_clim_type VALUES ('SANS', 'SANS', '');
INSERT INTO l_clim_type VALUES ('VENTIL', 'VENTILLATION', '');
INSERT INTO l_clim_type VALUES ('CLIM', 'CLIMATISATION', '');
INSERT INTO l_fo_color VALUES ('1', 'rouge (R)', '#FF0000');
INSERT INTO l_fo_color VALUES ('2', 'bleu (BL)', '#0070C0');
INSERT INTO l_fo_color VALUES ('3', 'vert (VE)', '#92D050');
INSERT INTO l_fo_color VALUES ('4', 'jaune (J)', '#FFFF00');
INSERT INTO l_fo_color VALUES ('5', 'violet (V)', '#7638A3');
INSERT INTO l_fo_color VALUES ('6', 'blanc (B)', '#FFFFFF');
INSERT INTO l_fo_color VALUES ('7', 'orange (OR)', '#FFC000');
INSERT INTO l_fo_color VALUES ('8', 'gris (GR)', '#C1C1C1');
INSERT INTO l_fo_color VALUES ('9', 'marron (BR)', '#993300');
INSERT INTO l_fo_color VALUES ('10', 'noir (N)', '#000000');
INSERT INTO l_fo_color VALUES ('11', 'turquoise (TU)', '#00B0F0');
INSERT INTO l_fo_color VALUES ('12', 'rose (RS)', '#FF65CC');
INSERT INTO l_connexion_type VALUES ('FO', 'FIBRE OPTIQUE', '');
INSERT INTO l_connexion_type VALUES ('CU', 'CUIVRE', '');
INSERT INTO l_connexion_type VALUES ('CO', 'COAXIAL', '');
INSERT INTO l_connexion_type VALUES ('FH', 'FAISCEAU HERTZIEN', '');
INSERT INTO l_doc_tab VALUES ('CB', 'CABLE', '');
INSERT INTO l_doc_tab VALUES ('FX', 'FOURREAU', '');
INSERT INTO l_doc_tab VALUES ('BP', 'ELEMENT BRANCHEMENT PASSIF', '');
INSERT INTO l_doc_tab VALUES ('MQ', 'MASQUE', '');
INSERT INTO l_doc_tab VALUES ('NO', 'NOEUD', '');
INSERT INTO l_doc_tab VALUES ('TR', 'TRANCHEE', '');
INSERT INTO l_doc_tab VALUES ('PT', 'POINT TECHNIQUE', '');
INSERT INTO l_doc_tab VALUES ('ST', 'SITE TECHNIQUE', '');
INSERT INTO l_doc_tab VALUES ('SF', 'SITEUTILISATEUR FINAL', '');
INSERT INTO l_doc_tab VALUES ('LT', 'LOCAL TECHNIQUE', '');
INSERT INTO l_doc_tab VALUES ('AD', 'ADRESSE', '');
INSERT INTO l_doc_tab VALUES ('BA', 'BAIE', '');
INSERT INTO l_doc_tab VALUES ('CS', 'CASSETTE', '');
INSERT INTO l_doc_tab VALUES ('EQ', 'EQUIPEMENT', '');
INSERT INTO l_doc_tab VALUES ('TI', 'TIROIR', '');
INSERT INTO l_doc_tab VALUES ('OR', 'ORGANISME', '');
INSERT INTO l_etat_type VALUES ('CRE', 'A CREER', '');
INSERT INTO l_etat_type VALUES ('CHG', 'A CHANGER', 'L''infrastructure doit être changée car la moindre intervention peut être préjudiciable à la fourniture du service');
INSERT INTO l_etat_type VALUES ('BAD', 'MAUVAIS ETAT', 'Mauvais état général de l''infrastructure qui ne permet pas certaines interventions');
INSERT INTO l_etat_type VALUES ('BON', 'BON ETAT', 'Bon état général qui permet de réaliser toute opération de maintenance, d''exploitation ou d''évolution');
INSERT INTO l_fibre_etat VALUES ('HS', 'HS', '');
INSERT INTO l_fibre_etat VALUES ('OK', 'FONCTIONNELLE', '');
INSERT INTO l_fx_type VALUES ('PEHD', 'PEHD', '');
INSERT INTO l_fx_type VALUES ('PVC', 'PVC', '');
INSERT INTO l_fx_type VALUES ('TPC', 'TPC', '');
INSERT INTO l_fx_type VALUES ('CUC', 'CONDUITE UNITAIRE CIMENT', '');
INSERT INTO l_fx_type VALUES ('AUTRE', 'AUTRE', '');
INSERT INTO l_fx_type VALUES ('NC', 'NON COMMUNIQUÉ', '');
INSERT INTO l_lgau_type VALUES ('CHAMBRE', 'CHAMBRE', '');
INSERT INTO l_lgau_type VALUES ('AERIEN', 'AERIEN', '');
INSERT INTO l_lgau_type VALUES ('FACADE', 'FACADE', '');
INSERT INTO l_lgau_type VALUES ('SPECIFIQUE', 'SPECIFIQUE', '');
INSERT INTO l_lgau_type VALUES ('EGOUT', 'EGOUT', '');
INSERT INTO l_lgau_type VALUES ('ENCORBELLEMENT', 'ENCORBELLEMENT', '');
INSERT INTO l_masque_face VALUES ('A', 'A', '');
INSERT INTO l_masque_face VALUES ('B', 'B', '');
INSERT INTO l_masque_face VALUES ('C', 'C', '');
INSERT INTO l_masque_face VALUES ('D', 'D', '');
INSERT INTO l_masque_face VALUES ('E', 'E', '');
INSERT INTO l_masque_face VALUES ('F', 'F', '');
INSERT INTO l_masque_face VALUES ('G', 'G', '');
INSERT INTO l_masque_face VALUES ('H', 'H', '');
INSERT INTO l_masque_face VALUES ('I', 'I', '');
INSERT INTO l_masque_face VALUES ('J', 'J', '');
INSERT INTO l_noeud_type VALUES ('P', 'PHYSIQUE', '');
INSERT INTO l_noeud_type VALUES ('S', 'SPECIFIQUE', '');
INSERT INTO l_occupation_type VALUES ('0', 'Vide', 'Infrastructure vide');
INSERT INTO l_occupation_type VALUES ('1.1', 'Non vide exploitable', 'Infrastructure non vide mais exploitable car rangée');
INSERT INTO l_occupation_type VALUES ('1.2', 'Non vide non exploitable', 'Infrastructure non vide mais non exploitable car non rangée');
INSERT INTO l_occupation_type VALUES ('2', 'Saturée', 'Infrastructure saturée');
INSERT INTO l_position_etat VALUES ('HS', 'HORS-SERVICE', '');
INSERT INTO l_position_etat VALUES ('ES', 'EN FONCTION', '');
INSERT INTO l_position_etat VALUES ('VE', 'A VERIFIER', '');
INSERT INTO l_position_fonction VALUES ('CO', 'CONNECTEUR', '');
INSERT INTO l_position_fonction VALUES ('EP', 'EPISSURE', '');
INSERT INTO l_position_fonction VALUES ('PI', 'PIGTAIL', '');
INSERT INTO l_position_fonction VALUES ('AT', 'ATTENTE', '');
INSERT INTO l_position_fonction VALUES ('PA', 'PASSAGE', '');
INSERT INTO l_position_fonction VALUES ('EJ', 'EPISSURE-JCD', '');
INSERT INTO l_position_fonction VALUES ('EH', 'EPISSURE-HDS', '');
INSERT INTO l_position_type VALUES ('SC', 'SC', 'CONNECTEUR');
INSERT INTO l_position_type VALUES ('EC', 'EC', 'CONNECTEUR');
INSERT INTO l_position_type VALUES ('FC', 'FC', 'CONNECTEUR');
INSERT INTO l_position_type VALUES ('FUSION', 'FUSION', 'SOUDURE');
INSERT INTO l_position_type VALUES ('MECANIQUE', 'MECANIQUE', 'SOUDURE');
INSERT INTO l_position_type VALUES ('LC', 'LC', 'CONNECTEUR');
INSERT INTO l_position_type VALUES ('ST', 'ST', 'CONNECTEUR');
INSERT INTO l_position_type VALUES ('SCAPC', 'SCAPC', 'CONNECTEUR');
INSERT INTO l_propriete_type VALUES ('CST', 'CONSTRUCTION', '');
INSERT INTO l_propriete_type VALUES ('RAC', 'RACHAT', '');
INSERT INTO l_propriete_type VALUES ('CES', 'CESSION', '');
INSERT INTO l_propriete_type VALUES ('IRU', 'IRU', '');
INSERT INTO l_propriete_type VALUES ('LOC', 'LOCATION', '');
INSERT INTO l_ptech_type VALUES ('A1', 'CHAMBRE A1', '');
INSERT INTO l_ptech_type VALUES ('A2', 'CHAMBRE A2', '');
INSERT INTO l_ptech_type VALUES ('A3', 'CHAMBRE A3', '');
INSERT INTO l_ptech_type VALUES ('A4', 'CHAMBRE A4', '');
INSERT INTO l_ptech_type VALUES ('B1', 'CHAMBRE B1', '');
INSERT INTO l_ptech_type VALUES ('B2', 'CHAMBRE B2', '');
INSERT INTO l_ptech_type VALUES ('B3', 'CHAMBRE B3', '');
INSERT INTO l_ptech_type VALUES ('B4', 'CHAMBRE B4', '');
INSERT INTO l_ptech_type VALUES ('C1', 'CHAMBRE C1', '');
INSERT INTO l_ptech_type VALUES ('C2', 'CHAMBRE C2', '');
INSERT INTO l_ptech_type VALUES ('C3', 'CHAMBRE C3', '');
INSERT INTO l_ptech_type VALUES ('C4', 'CHAMBRE C4', '');
INSERT INTO l_ptech_type VALUES ('D1', 'CHAMBRE D1', '');
INSERT INTO l_ptech_type VALUES ('D2', 'CHAMBRE D2', '');
INSERT INTO l_ptech_type VALUES ('D3', 'CHAMBRE D3', '');
INSERT INTO l_ptech_type VALUES ('D4', 'CHAMBRE D4', '');
INSERT INTO l_ptech_type VALUES ('E1', 'CHAMBRE E1', '');
INSERT INTO l_ptech_type VALUES ('E2', 'CHAMBRE E2', '');
INSERT INTO l_ptech_type VALUES ('E3', 'CHAMBRE E3', '');
INSERT INTO l_ptech_type VALUES ('E4', 'CHAMBRE E4', '');
INSERT INTO l_ptech_type VALUES ('J2C', 'CHAMBRE J2C', '');
INSERT INTO l_ptech_type VALUES ('J2CR', 'CHAMBRE J2CR', '');
INSERT INTO l_ptech_type VALUES ('K1C', 'CHAMBRE K1C', '');
INSERT INTO l_ptech_type VALUES ('K1CR', 'CHAMBRE K1CR', '');
INSERT INTO l_ptech_type VALUES ('K2C', 'CHAMBRE K2C', '');
INSERT INTO l_ptech_type VALUES ('K2CR', 'CHAMBRE K2CR', '');
INSERT INTO l_ptech_type VALUES ('K3C', 'CHAMBRE K3C', '');
INSERT INTO l_ptech_type VALUES ('K3CR', 'CHAMBRE K3CR', '');
INSERT INTO l_ptech_type VALUES ('L0T', 'CHAMBRE L0T', '');
INSERT INTO l_ptech_type VALUES ('L0TR', 'CHAMBRE L0TR', '');
INSERT INTO l_ptech_type VALUES ('L1C', 'CHAMBRE L1C', '');
INSERT INTO l_ptech_type VALUES ('L1T', 'CHAMBRE L1T', '');
INSERT INTO l_ptech_type VALUES ('L1TR', 'CHAMBRE L1TR', '');
INSERT INTO l_ptech_type VALUES ('L2C', 'CHAMBRE L2C', '');
INSERT INTO l_ptech_type VALUES ('L2T', 'CHAMBRE L2T', '');
INSERT INTO l_ptech_type VALUES ('L2TR', 'CHAMBRE L2TR', '');
INSERT INTO l_ptech_type VALUES ('L3C', 'CHAMBRE L3C', '');
INSERT INTO l_ptech_type VALUES ('L3T', 'CHAMBRE L3T', '');
INSERT INTO l_ptech_type VALUES ('L3TR', 'CHAMBRE L3TR', '');
INSERT INTO l_ptech_type VALUES ('L4C', 'CHAMBRE L4C', '');
INSERT INTO l_ptech_type VALUES ('L4T', 'CHAMBRE L4T', '');
INSERT INTO l_ptech_type VALUES ('L4TR', 'CHAMBRE L4TR', '');
INSERT INTO l_ptech_type VALUES ('L5C', 'CHAMBRE L5C', '');
INSERT INTO l_ptech_type VALUES ('L5T', 'CHAMBRE L5T', '');
INSERT INTO l_ptech_type VALUES ('L5TR', 'CHAMBRE L5TR', '');
INSERT INTO l_ptech_type VALUES ('L6T', 'CHAMBRE L6T', '');
INSERT INTO l_ptech_type VALUES ('L6TR', 'CHAMBRE L6TR', '');
INSERT INTO l_ptech_type VALUES ('M1C', 'CHAMBRE M1C', '');
INSERT INTO l_ptech_type VALUES ('M1CR', 'CHAMBRE M1CR', '');
INSERT INTO l_ptech_type VALUES ('M2T', 'CHAMBRE M2T', '');
INSERT INTO l_ptech_type VALUES ('M2TR', 'CHAMBRE M2TR', '');
INSERT INTO l_ptech_type VALUES ('M3C', 'CHAMBRE M3C', '');
INSERT INTO l_ptech_type VALUES ('M3CR', 'CHAMBRE M3CR', '');
INSERT INTO l_ptech_type VALUES ('P1C', 'CHAMBRE P1C', '');
INSERT INTO l_ptech_type VALUES ('P1CR', 'CHAMBRE P1CR', '');
INSERT INTO l_ptech_type VALUES ('P1T', 'CHAMBRE P1T', '');
INSERT INTO l_ptech_type VALUES ('P1TR', 'CHAMBRE P1TR', '');
INSERT INTO l_ptech_type VALUES ('P2C', 'CHAMBRE P2C', '');
INSERT INTO l_ptech_type VALUES ('P2CR', 'CHAMBRE P2CR', '');
INSERT INTO l_ptech_type VALUES ('P2T', 'CHAMBRE P2T', '');
INSERT INTO l_ptech_type VALUES ('P2TR', 'CHAMBRE P2TR', '');
INSERT INTO l_ptech_type VALUES ('PBOI', 'POTEAU BOIS', '');
INSERT INTO l_ptech_type VALUES ('PBET', 'POTEAU BETON', '');
INSERT INTO l_ptech_type VALUES ('PMET', 'POTEAU METAL', '');
INSERT INTO l_ptech_type VALUES ('PIND', 'POTEAU INDETERMINE', '');
INSERT INTO l_ptech_type VALUES ('POTL', 'POTELET', '');
INSERT INTO l_ptech_type VALUES ('R1T', 'CHAMBRE R1T', '');
INSERT INTO l_ptech_type VALUES ('R2T', 'CHAMBRE R2T', '');
INSERT INTO l_ptech_type VALUES ('R3T', 'CHAMBRE R3T', '');
INSERT INTO l_ptech_type VALUES ('BOU', 'BOUCHON', '');
INSERT INTO l_ptech_type VALUES ('REG', 'REGARD 30X30', '');
INSERT INTO l_ptech_type VALUES ('OHN', 'OUVRAGE HORS NORMES', '');
INSERT INTO l_ptech_type VALUES ('TRA', 'TRAVERSE', '');
INSERT INTO l_ptech_type VALUES ('CRO', 'CROCHET', '');
INSERT INTO l_ptech_type VALUES ('BAL', 'BALCON', '');
INSERT INTO l_ptech_type VALUES ('FAI', 'FAITIERE', '');
INSERT INTO l_ptech_type VALUES ('STR', 'SOUTERRAIN', '');
INSERT INTO l_ptech_type VALUES ('SSO', 'SOUS-SOL', '');
INSERT INTO l_ptech_type VALUES ('Y', 'SITE MANCHONNAGE Y', 'Fenêtre ouverture sur fourreaux existant pour mise en Y');
INSERT INTO l_ptech_type VALUES ('IND', 'INDETERMINE', '');
INSERT INTO l_ptech_usage_type VALUES ('T', 'TIRAGE', '');
INSERT INTO l_ptech_usage_type VALUES ('R', 'RACCORDEMENT', '');
INSERT INTO l_qualite_info VALUES ('VA', 'VALIDE', '');
INSERT INTO l_qualite_info VALUES ('TH', 'THEORIQUE', '');
INSERT INTO l_qualite_info VALUES ('NC', 'NON COMMUNIQUE', '');
INSERT INTO l_qualitegeolocalisation VALUES ('1', 'Topologie traditionnelle ou GPS centimétrique', 'Précision < 10cm');
INSERT INTO l_qualitegeolocalisation VALUES ('2', 'GPS submétrique', 'Précision < 1m');
INSERT INTO l_qualitegeolocalisation VALUES ('3', 'GPS métrique', 'Précision > 1m');
INSERT INTO l_qualitegeolocalisation VALUES ('4', 'Numérisation sur orthophotographie', 'Précision (3 à 5 m)');
INSERT INTO l_qualitegeolocalisation VALUES ('5', 'GPS grand public', 'Précision faible > 5 m');
INSERT INTO l_reference_etat VALUES ('A', 'ACTIVE', '');
INSERT INTO l_reference_etat VALUES ('N', 'NON DISPONIBLE', '');
INSERT INTO l_reference_type VALUES ('BA', 'BAIE', '');
INSERT INTO l_reference_type VALUES ('BP', 'BPE', '');
INSERT INTO l_reference_type VALUES ('CA', 'CABLE', '');
INSERT INTO l_reference_type VALUES ('CS', 'CASSETTE', '');
INSERT INTO l_reference_type VALUES ('EQ', 'EQUIPEMENT', '');
INSERT INTO l_reference_type VALUES ('PT', 'POINT TECHNIQUE', '');
INSERT INTO l_reference_type VALUES ('TI', 'TIROIR', '');
INSERT INTO l_site_emission_type VALUES ('RADIO', 'RadioDiffusion', '');
INSERT INTO l_site_emission_type VALUES ('TEL', 'Radio Téléphonie', '');
INSERT INTO l_site_emission_type VALUES ('BLR', 'Boucle locale Radio', '');
INSERT INTO l_site_emission_type VALUES ('FH', 'Faisceau Hertzien', '');
INSERT INTO l_site_emission_type VALUES ('WIFI', 'Wifi', '');
INSERT INTO l_site_emission_type VALUES ('WIMAX', 'Wimax', '');
INSERT INTO l_site_type VALUES ('NRA', 'NŒUD RACCORDEMENT D''ABONNÉS', '');
INSERT INTO l_site_type VALUES ('NRAHD', 'NŒUD RACCORDEMENT D''ABONNÉS - HAUT DÉBIT', '');
INSERT INTO l_site_type VALUES ('NRAMED', 'NŒUD RACCORDEMENT D''ABONNÉS - MONTÉE EN DÉBIT', '');
INSERT INTO l_site_type VALUES ('NRAZO', 'NŒUD RACCORDEMENT D''ABONNÉS - ZONE D''OMBRE', '');
INSERT INTO l_site_type VALUES ('SRP', 'SOUS-REPARTITEUR CUIVRE PRIMAIRE', '');
INSERT INTO l_site_type VALUES ('SRS', 'SOUS-REPARTITEUR CUIVRE SECONDAIRE', '');
INSERT INTO l_site_type VALUES ('SRT', 'SOUS-REPARTITEUR CUIVRE TERTIAIRE', '');
INSERT INTO l_site_type VALUES ('NRO', 'NŒUD RACCORDEMENT OPTIQUE', '');
INSERT INTO l_site_type VALUES ('SRO', 'SOUS-REPARTITEUR OPTIQUE', '');
INSERT INTO l_site_type VALUES ('BRASSAGE', 'SITE DE BRASSAGE', 'Site non prévu pour héberger des équipements actifs (surtout longue distance)');
INSERT INTO l_site_type VALUES ('CLIENT', 'SITE CLIENT', 'Site entreprise ou administration qui n''est pas un site utilisateur final (SUF). ');
INSERT INTO l_site_type VALUES ('HEBERG', 'SITE HEBERGEMENT', 'Site d''hébergement d''équipements actifs qui n''est pas un NRO (hors architecture FTTH). ');
INSERT INTO l_site_type_structurel VALUES ('ADR', 'ARMOIRE DE RUE', '');
INSERT INTO l_site_type_structurel VALUES ('BAT', 'BATIMENT', '');
INSERT INTO l_site_type_structurel VALUES ('SHE', 'SHELTER', '');
INSERT INTO l_statut VALUES ('SDI', 'SCHEMA INGENIERIE', '');
INSERT INTO l_statut VALUES ('APS', 'APS', '');
INSERT INTO l_statut VALUES ('APD', 'APD', '');
INSERT INTO l_statut VALUES ('PRE', 'PRE', '');
INSERT INTO l_statut VALUES ('DOE', 'DOE', '');
INSERT INTO l_suf_type VALUES ('R', 'RESIDENTIEL', '');
INSERT INTO l_suf_type VALUES ('P', 'PROFESSIONNEL', '');
INSERT INTO l_suf_type VALUES ('O', 'OPERATEUR', '');
INSERT INTO l_suf_type VALUES ('T', 'TECHNIQUE', '');
INSERT INTO l_suf_type VALUES ('S', 'SDS', '');
INSERT INTO l_suf_type VALUES ('C', 'SSC', '');
INSERT INTO l_technologie_type VALUES ('CUT', 'CUIVRE TÉLÉCOM', '');
INSERT INTO l_technologie_type VALUES ('OPT', 'OPTIQUE', '');
INSERT INTO l_technologie_type VALUES ('COA', 'COAXIAL', '');
INSERT INTO l_technologie_type VALUES ('ECL', 'ECLAIRAGE', '');
INSERT INTO l_technologie_type VALUES ('ELE', 'ELECTRICITÉ', '');
INSERT INTO l_technologie_type VALUES ('VID', 'VIDEO PROTEXTION', '');
INSERT INTO l_tiroir_type VALUES ('TIROIR', 'TIROIR', '');
INSERT INTO l_tiroir_type VALUES ('TETE', 'TETE DE CABLE', '');
INSERT INTO l_tranchee_implantation_type VALUES ('ACC', 'ACCOTEMENT', '');
INSERT INTO l_tranchee_implantation_type VALUES ('CHAU', 'CHAUSSÉE', '');
INSERT INTO l_tranchee_implantation_type VALUES ('TROT', 'TROTTOIR', '');
INSERT INTO l_tranchee_implantation_type VALUES ('TER', 'TERRE', '');
INSERT INTO l_tranchee_implantation_type VALUES ('EMP', 'EMPIERRE', '');
INSERT INTO l_tranchee_implantation_type VALUES ('PON', 'PONT', '');
INSERT INTO l_tranchee_implantation_type VALUES ('SNC', 'PASSAGE SNCF', '');
INSERT INTO l_tranchee_implantation_type VALUES ('CAN', 'CANIVEAU TECHNIQUE', '');
INSERT INTO l_tranchee_implantation_type VALUES ('PAV', 'PAVÉS', '');
INSERT INTO l_tranchee_implantation_type VALUES ('NC', 'NON COMMUNIQUÉ', '');
INSERT INTO l_tranchee_pose_type VALUES ('NC', 'NON COMMUNIQUÉ', '');
INSERT INTO l_tranchee_pose_type VALUES ('TRA', 'TRADITIONNELLE', '');
INSERT INTO l_tranchee_pose_type VALUES ('MEC', 'MÉCANISÉE', '');
INSERT INTO l_tranchee_pose_type VALUES ('MIC', 'MICRO TRANCHÉE', '');
INSERT INTO l_tranchee_pose_type VALUES ('FOR', 'FORAGE DIRIGÉ', '');
INSERT INTO l_tranchee_pose_type VALUES ('ENS', 'ENSOUILLAGE', '');
INSERT INTO l_tranchee_pose_type VALUES ('FON', 'FONÇAGE', '');
INSERT INTO l_tranchee_pose_type VALUES ('ENC', 'ENCORBELLEMENT', '');
INSERT INTO l_tranchee_pose_type VALUES ('STU', 'SOUS-TUBAGE', 'Sous-tubage infra existante');
INSERT INTO l_tranchee_type VALUES ('1', 'ACCOTEMENT NON REVETU', 'TRANCHEE MECANISEE MINI');
INSERT INTO l_tranchee_type VALUES ('2', 'ACCOTEMENT NON REVETU', 'TRANCHEE MECANISEE MINI');
INSERT INTO l_tranchee_type VALUES ('3', 'ACCOTEMENT NON REVETU', 'TRANCHEE MECANISEE MINI');
INSERT INTO l_tranchee_type VALUES ('4', 'ACCOTEMENT NON REVETU', 'TRANCHEE MECANISEE MICRO-RIVE');
INSERT INTO l_tranchee_type VALUES ('5', 'TROTTOIR OU ACCOTEMENT REVETU', 'TRANCHEE TRADITIONNELLE');
INSERT INTO l_tranchee_type VALUES ('6', 'TROTTOIR OU ACCOTEMENT REVETU', 'TRANCHEE MECANISEE MINI-MICRO');
INSERT INTO l_tranchee_type VALUES ('7', 'CHAUSSEE T3/T4/T5', 'TRANCHEE MECANISEE MINI');
INSERT INTO l_tranchee_type VALUES ('8', 'CHAUSSEE T3/T4/T5', 'TRANCHEE MECANISEE MICRO');
INSERT INTO l_tranchee_type VALUES ('9', 'CHAUSSEE T1/T2', 'TRANCHEE MECANISEE MINI');
INSERT INTO l_tranchee_type VALUES ('10', 'CHAUSSEE T1/T2', 'TRANCHEE MECANISEE MICRO');
INSERT INTO l_tranchee_type VALUES ('11', 'CHAUSSEE T1/T2', 'TRANCHEE TRADITIONNELLE');
INSERT INTO l_tranchee_type VALUES ('12', 'CHAUSSEE T3', 'TRANCHEE TRADITIONNELLE');
INSERT INTO l_tranchee_type VALUES ('13', 'CHAUSSEE T4/T5', 'TRANCHEE TRADITIONNELLE');
INSERT INTO l_tranchee_type VALUES ('14', 'CHEMIN EMPIERRE', 'TRANCHEE TRADITIONNELLE');
INSERT INTO l_tranchee_type VALUES ('15', 'CHEMIN EMPIERRE', 'TRANCHEE MECANISEE MINI-MICRO');
INSERT INTO l_tranchee_type VALUES ('16', 'ESPACE VERT', 'TRANCHEE TRADITIONNELLE');
INSERT INTO l_tube VALUES ('1', 'SOUS FAISCEAU ROUGE UNE BAGUE COURTE', '');
INSERT INTO l_tube VALUES ('2', 'SOUS FAISCEAU BLEU DEUX BAGUES COURTES', '');
INSERT INTO l_tube VALUES ('3', 'SOUS FAISCEAU VERT TROIS BAGUES COURTES', '');
INSERT INTO l_tube VALUES ('4', 'SOUS FAISCEAU JAUNE QUATRE BAGUES COURTES', '');
INSERT INTO l_tube VALUES ('5', 'SOUS FAISCEAU VIOLET UNE BAGUE LONGUE', '');
INSERT INTO l_tube VALUES ('6', 'SOUS FAISCEAU BLANC UNE BAGUE LONGUE ET UNE BAGUE COURTE', '');
INSERT INTO l_type_bati VALUES ('1', 'MONO-SITE', '');
INSERT INTO l_type_bati VALUES ('2', 'MULTI-SITE', '');
INSERT INTO l_zo_type VALUES ('NC', 'NON COMMUNIQUÉ', '');
INSERT INTO l_zo_type VALUES ('ZANRO', 'ZONE ARRIERE NOEUD DE RACCARODEMENT OPTIQUE', '');
INSERT INTO l_zo_type VALUES ('ZAPM', 'ZONE ARRIERE DE POINT MUTUALISATION', '');
INSERT INTO l_zo_type VALUES ('ZAPBO', 'ZONE ARRIERE POINT DE BRANCHEMENT OPTIQUE', '');
INSERT INTO l_zo_type VALUES ('ZC', 'ZONE CABLO-OPERATEUR', '');
INSERT INTO l_zo_type VALUES ('ZA', 'ZONE AMENAGEMENT', '');
INSERT INTO l_zo_type VALUES ('ZF', 'ZONE FIBREE', 'Amendement Loi Macron');
COMMIT;
