DROP TABLE IF EXISTS l_fibre_etat;
DROP TABLE IF EXISTS l_fx_type;
DROP TABLE IF EXISTS l_lgau_type;
DROP TABLE IF EXISTS l_masque_face;
DROP TABLE IF EXISTS l_noeud_type;
DROP TABLE IF EXISTS l_occupation_type;
DROP TABLE IF EXISTS l_position_etat;
DROP TABLE IF EXISTS l_position_fonction;
DROP TABLE IF EXISTS l_position_type;
DROP TABLE IF EXISTS l_propriete_type;
DROP TABLE IF EXISTS l_ptech_type;
DROP TABLE IF EXISTS l_ptech_usage_type;
DROP TABLE IF EXISTS l_qualite_info;
DROP TABLE IF EXISTS l_qualitegeolocalisation;
DROP TABLE IF EXISTS l_reference_etat;
DROP TABLE IF EXISTS l_reference_type;
DROP TABLE IF EXISTS l_site_emission_type;
DROP TABLE IF EXISTS l_site_type;
DROP TABLE IF EXISTS l_site_type_structurel;
DROP TABLE IF EXISTS l_statut;
DROP TABLE IF EXISTS l_suf_type;
DROP TABLE IF EXISTS l_technologie_cable_type;
DROP TABLE IF EXISTS l_technologie_type;
DROP TABLE IF EXISTS l_tiroir_type;
DROP TABLE IF EXISTS l_tranchee_implantation_type;
DROP TABLE IF EXISTS l_tranchee_pose_type;
DROP TABLE IF EXISTS l_tranchee_type;
DROP TABLE IF EXISTS l_tube;
DROP TABLE IF EXISTS l_type_bati;
DROP TABLE IF EXISTS l_zo_type;

CREATE TABLE l_accessibilite_type(code VARCHAR(10), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_accessibilite_type_pk" PRIMARY KEY (code));
CREATE TABLE l_adress_etat(code VARCHAR(10), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_adress_etat_pk" PRIMARY KEY (code));
CREATE TABLE l_adress_type(code VARCHAR(10), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_adress_type_pk" PRIMARY KEY (code));
CREATE TABLE l_artere_implantation_type(code VARCHAR(2), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_artere_implantation_type_pk" PRIMARY KEY (code));
CREATE TABLE l_artere_nature(code VARCHAR(3), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_artere_nature_pk" PRIMARY KEY (code));
CREATE TABLE l_artere_type(code VARCHAR(2), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_artere_type_pk" PRIMARY KEY (code));
CREATE TABLE l_baie_type(code VARCHAR(10), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_baie_type_pk" PRIMARY KEY (code));
CREATE TABLE l_bp_localisation(code VARCHAR(10), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_bp_localisation_pk" PRIMARY KEY (code));
CREATE TABLE l_bp_racco(code VARCHAR(10), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_bp_racco_pk" PRIMARY KEY (code));
CREATE TABLE l_bp_type(code VARCHAR(10), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_bp_type_pk" PRIMARY KEY (code));
CREATE TABLE l_cable_type(code VARCHAR(10), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_cable_type_pk" PRIMARY KEY (code));
CREATE TABLE l_cassette_type(code VARCHAR(10), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_cassette_type_pk" PRIMARY KEY (code));
CREATE TABLE l_clim_type(code VARCHAR(10), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_clim_type_pk" PRIMARY KEY (code));
CREATE TABLE l_fo_color(code VARCHAR(10), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_fo_color_pk" PRIMARY KEY (code));
CREATE TABLE l_connexion_type(code VARCHAR(2), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_connexion_type_pk" PRIMARY KEY (code));
CREATE TABLE l_doc_tab(code VARCHAR(2), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_doc_tab_pk" PRIMARY KEY (code));
CREATE TABLE l_etat_type(code VARCHAR(3), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_etat_type_pk" PRIMARY KEY (code));
CREATE TABLE l_fibre_etat(code VARCHAR(2), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_fibre_etat_pk" PRIMARY KEY (code));
CREATE TABLE l_fx_type(code VARCHAR(10), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_fx_type_pk" PRIMARY KEY (code));
CREATE TABLE l_lgau_type(code VARCHAR(20), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_lgau_type_pk" PRIMARY KEY (code));
CREATE TABLE l_masque_face(code VARCHAR(2), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_masque_face_pk" PRIMARY KEY (code));
CREATE TABLE l_noeud_type(code VARCHAR(2), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_noeud_type_pk" PRIMARY KEY (code));
CREATE TABLE l_occupation_type(code VARCHAR(10), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_occupation_type_pk" PRIMARY KEY (code));
CREATE TABLE l_position_etat(code VARCHAR(2), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_position_etat_pk" PRIMARY KEY (code));
CREATE TABLE l_position_fonction(code VARCHAR(2), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_position_fonction_pk" PRIMARY KEY (code));
CREATE TABLE l_position_type(code VARCHAR(10), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_position_type_pk" PRIMARY KEY (code));
CREATE TABLE l_propriete_type(code VARCHAR(3), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_propriete_type_pk" PRIMARY KEY (code));
CREATE TABLE l_ptech_type(code VARCHAR(20), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_ptech_type_pk" PRIMARY KEY (code));
CREATE TABLE l_ptech_usage_type(code VARCHAR(1), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_ptech_usage_type_pk" PRIMARY KEY (code));
CREATE TABLE l_qualite_info(code VARCHAR(3), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_qualite_info_pk" PRIMARY KEY (code));
CREATE TABLE l_qualitegeolocalisation(code VARCHAR(2), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_qualitegeolocalisation_pk" PRIMARY KEY (code));
CREATE TABLE l_reference_etat(code VARCHAR(2), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_reference_etat_pk" PRIMARY KEY (code));
CREATE TABLE l_reference_type(code VARCHAR(2), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_reference_type_pk" PRIMARY KEY (code));
CREATE TABLE l_site_emission_type(code VARCHAR(10), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_site_emission_type_pk" PRIMARY KEY (code));
CREATE TABLE l_site_type(code VARCHAR(10), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_site_type_pk" PRIMARY KEY (code));
CREATE TABLE l_site_type_structurel(code VARCHAR(3), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_site_type_structurel_pk" PRIMARY KEY (code));
CREATE TABLE l_statut(code VARCHAR(3), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_statut_pk" PRIMARY KEY (code));
CREATE TABLE l_suf_type(code VARCHAR(1), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_suf_type_pk" PRIMARY KEY (code));
CREATE TABLE l_technologie_cable_type(code VARCHAR(2), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_technologie_cable_type_pk" PRIMARY KEY (code));
CREATE TABLE l_technologie_type(code VARCHAR(10), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_technologie_type_pk" PRIMARY KEY (code));
CREATE TABLE l_tiroir_type(code VARCHAR(10), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_tiroir_type_pk" PRIMARY KEY (code));
CREATE TABLE l_tranchee_implantation_type(code VARCHAR(10), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_tranchee_implantation_type_pk" PRIMARY KEY (code));
CREATE TABLE l_tranchee_pose_type(code VARCHAR(20), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_tranchee_pose_type_pk" PRIMARY KEY (code));
CREATE TABLE l_tranchee_type(code VARCHAR(5), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_tranchee_type_pk" PRIMARY KEY (code));
CREATE TABLE l_tube(code VARCHAR(5), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_tube_pk" PRIMARY KEY (code));
CREATE TABLE l_type_bati(code VARCHAR(1), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_type_bati_pk" PRIMARY KEY (code));
CREATE TABLE l_zo_type(code VARCHAR(10), libelle VARCHAR(254), definition VARCHAR(254), CONSTRAINT "l_zo_type_pk" PRIMARY KEY (code));
