/*GraceTHD v2 beta1b*/
/*Insertion des valeurs dans les listes de valeurs*/
/*Spatialite*/

BEGIN;
INSERT INTO l_adresse_etat VALUES ('CI', 'CIBLE', '');
INSERT INTO l_adresse_etat VALUES ('SI', 'SIGNE', '');
INSERT INTO l_adresse_etat VALUES ('EC', 'EN COURS DE DEPLOIEMENT', '');
INSERT INTO l_adresse_etat VALUES ('DE', 'DEPLOYE', '');
INSERT INTO l_adresse_etat VALUES ('AB', 'ABANDONNE', '');
INSERT INTO l_baie_type VALUES ('BAIE', 'BAIE', '');
INSERT INTO l_baie_type VALUES ('FERME', 'FERME', '');
INSERT INTO l_bp_racco VALUES ('CLI001', '', '');
INSERT INTO l_bp_racco VALUES ('CLI002', 'CLIENT INJOIGNABLE IMPOSSIBLE DE PRENDRE RDV', '');
INSERT INTO l_bp_racco VALUES ('CLI003', '', '');
INSERT INTO l_bp_racco VALUES ('CLI004', '', '');
INSERT INTO l_bp_racco VALUES ('CLI005', 'CLIENT REFUS CLIENT', '');
INSERT INTO l_bp_racco VALUES ('CLI006', 'CLIENT REFUS GESTIONNAIRE D IMMEUBLES', '');
INSERT INTO l_bp_racco VALUES ('CLI007', 'CLIENT ABSENCE CLIENT LORS DE L INTERVENTION', '');
INSERT INTO l_bp_racco VALUES ('ADR001', '', '');
INSERT INTO l_bp_racco VALUES ('ADR002', '', '');
INSERT INTO l_bp_racco VALUES ('ADR003', '', '');
INSERT INTO l_bp_racco VALUES ('ADR004', '', '');
INSERT INTO l_bp_racco VALUES ('ADR005', '', '');
INSERT INTO l_bp_racco VALUES ('ADR006', '', '');
INSERT INTO l_bp_racco VALUES ('IMP001', '', '');
INSERT INTO l_bp_racco VALUES ('IMP002', 'PB OU PM SATURE', '');
INSERT INTO l_bp_racco VALUES ('IMP003', '', '');
INSERT INTO l_bp_racco VALUES ('IMP004', 'COMMANDE IMPOSSIBLE :  IDENTIFIANT INTERNE OC INCONNUE', '');
INSERT INTO l_bp_racco VALUES ('IMP005', 'FORMAT ERRONE', '');
INSERT INTO l_bp_racco VALUES ('IMP006', 'CHAMPS OBLIGATOIRES MANQUANTS', '');
INSERT INTO l_bp_racco VALUES ('INT001', 'HL OI : HOTLINE OI INJOIGNABLE', '');
INSERT INTO l_bp_racco VALUES ('INT002', 'ABSENCE DE CONTINUITE OPTIQUE', '');
INSERT INTO l_bp_racco VALUES ('INT003', 'AFFAIBLISSEMENT TROP IMPORTANT', '');
INSERT INTO l_bp_racco VALUES ('AUT001', 'AUTRE MOTIF : COMMENTAIRES LIBRES', '');
INSERT INTO l_bp_racco VALUES ('RDV01', 'NOMBRE DE MODIFICATIONS MAX DEPASSE', '');
INSERT INTO l_bp_racco VALUES ('RDV02', '', '');
INSERT INTO l_bp_racco VALUES ('RDV03', 'COMMANDE GELEE', '');
INSERT INTO l_bp_racco VALUES ('RACOK', 'PRISE RACCORDEE', '');
INSERT INTO l_bp_type_log VALUES ('BPE', 'BOITIER PROTECTION EPISSURE', '');
INSERT INTO l_bp_type_log VALUES ('PTO', 'POINT DE TERMINAISON OPTIQUE', '');
INSERT INTO l_bp_type_log VALUES ('PBO', 'POINT DE BRANCHEMENT OPTIQUE', '');
INSERT INTO l_bp_type_phy VALUES ('B006', 'BPE 6FO', '');
INSERT INTO l_bp_type_phy VALUES ('B012', 'BPE 12FO', '');
INSERT INTO l_bp_type_phy VALUES ('B024', 'BPE 24FO', '');
INSERT INTO l_bp_type_phy VALUES ('B048', 'BPE 48FO', '');
INSERT INTO l_bp_type_phy VALUES ('B072', 'BPE 72FO', '');
INSERT INTO l_bp_type_phy VALUES ('B096', 'BPE 96FO', '');
INSERT INTO l_bp_type_phy VALUES ('B144', 'BPE 144FO', '');
INSERT INTO l_bp_type_phy VALUES ('B288', 'BPE 288FO', '');
INSERT INTO l_bp_type_phy VALUES ('B576', 'BPE 576FO', '');
INSERT INTO l_bp_type_phy VALUES ('AUTR', 'AUTRE', '');
INSERT INTO l_cable_type VALUES ('C', 'CABLE', '');
INSERT INTO l_cable_type VALUES ('B', 'BREAKOUT', '');
INSERT INTO l_cable_type VALUES ('J', 'JARRETIERE', '');
INSERT INTO l_cassette_type VALUES ('P', 'PLATEAU DE LOVAGE BPE', '');
INSERT INTO l_cassette_type VALUES ('E', 'EPISSURE', '');
INSERT INTO l_cassette_type VALUES ('S', 'SPLITTER', '');
INSERT INTO l_cassette_type VALUES ('C', 'CONNECTEUR', '');
INSERT INTO l_clim_type VALUES ('SANS', 'SANS', '');
INSERT INTO l_clim_type VALUES ('VENTIL', 'VENTILLATION', '');
INSERT INTO l_clim_type VALUES ('CLIM', 'CLIMATISATION', '');
INSERT INTO l_conduite_type VALUES ('PEHD', 'PEHD', '');
INSERT INTO l_conduite_type VALUES ('PVC', 'PVC', '');
INSERT INTO l_conduite_type VALUES ('TPC', 'TPC', '');
INSERT INTO l_conduite_type VALUES ('CUC', 'CONDUITE UNITAIRE CIMENT', '');
INSERT INTO l_conduite_type VALUES ('CAN', 'ALVEOLE DE CANIVEAU', 'Possibilite de realiser des masques pour les caniveaux. ');
INSERT INTO l_conduite_type VALUES ('GOU', 'ALVEOLE DE GOULOTTE', 'Possibilite de realiser des masques pour les goulottes avec multiples alveoles. ');
INSERT INTO l_conduite_type VALUES ('AER', 'CONDUITE AERIENNE VIRTUELLE', 'Utilise pour creer la relation entre le cable et le cheminement dans le cas de cheminement aerien. ');
INSERT INTO l_conduite_type VALUES ('AUTRE', 'AUTRE', '');
INSERT INTO l_conduite_type VALUES ('NC', 'NON COMMUNIQUE', '');
INSERT INTO l_doc_tab VALUES ('CB', 'CABLE', '');
INSERT INTO l_doc_tab VALUES ('CD', 'CONDUITE', '');
INSERT INTO l_doc_tab VALUES ('BP', 'ELEMENT BRANCHEMENT PASSIF', '');
INSERT INTO l_doc_tab VALUES ('MQ', 'MASQUE', '');
INSERT INTO l_doc_tab VALUES ('ND', 'NOEUD', '');
INSERT INTO l_doc_tab VALUES ('PT', 'POINT TECHNIQUE', '');
INSERT INTO l_doc_tab VALUES ('ST', 'SITE TECHNIQUE', '');
INSERT INTO l_doc_tab VALUES ('SF', 'SITEUTILISATEUR FINAL', '');
INSERT INTO l_doc_tab VALUES ('LT', 'LOCAL TECHNIQUE', '');
INSERT INTO l_doc_tab VALUES ('AD', 'ADRESSE', '');
INSERT INTO l_doc_tab VALUES ('BA', 'BAIE', '');
INSERT INTO l_doc_tab VALUES ('CS', 'CASSETTE', '');
INSERT INTO l_doc_tab VALUES ('EQ', 'EQUIPEMENT', '');
INSERT INTO l_doc_tab VALUES ('TI', 'TIROIR', '');
INSERT INTO l_doc_tab VALUES ('OR', 'ORGANISME', '');
INSERT INTO l_doc_tab VALUES ('ZN', 'ZONE DE NRO', '');
INSERT INTO l_doc_tab VALUES ('ZD', 'ZONE DE DEPLOIEMENT', '');
INSERT INTO l_doc_tab VALUES ('ZS', 'ZONE DE SRO', '');
INSERT INTO l_doc_tab VALUES ('RF', 'REFERENCE', '');
INSERT INTO l_doc_tab VALUES ('RT', 'ROUTE OPTIQUE', '');
INSERT INTO l_doc_tab VALUES ('CM', 'CHEMINEMENT', '');
INSERT INTO l_doc_tab VALUES ('FO', 'FIBRE', '');
INSERT INTO l_doc_tab VALUES ('PS', 'POSITION', '');
INSERT INTO l_doc_tab VALUES ('SE', 'SITE EMISSION', '');
INSERT INTO l_doc_tab VALUES ('LV', 'LOVE', '');
INSERT INTO l_doc_tab VALUES ('ZP', 'ZONE ARRIERE DE PBO', '');
INSERT INTO l_doc_tab VALUES ('ZC', 'ZONE COAX', '');
INSERT INTO l_doc_type VALUES ('DIG', 'DOSSIER D INGENIERIE : REGLES D INGENIERIE UTILISEES', '');
INSERT INTO l_doc_type VALUES ('ETU', 'RAPPORT D ETUDE', '');
INSERT INTO l_doc_type VALUES ('PSI', 'PLAN DE SITUATION, SYNOPTIQUE GEOGRAPHIQUE', '');
INSERT INTO l_doc_type VALUES ('PPH', 'PLAN DE PHASAGE', '');
INSERT INTO l_doc_type VALUES ('PCB', 'PLAN DE CABLAGE', '');
INSERT INTO l_doc_type VALUES ('PMQ', 'PLAN DE MASQUE OU FICHE FOA', '');
INSERT INTO l_doc_type VALUES ('DPO', 'DOSSIER APPUIS AERIENS', '');
INSERT INTO l_doc_type VALUES ('FOT', 'PHOTO', '');
INSERT INTO l_doc_type VALUES ('PGC', 'PLAN DE GENIE CIVIL', '');
INSERT INTO l_doc_type VALUES ('DLV', 'DOSSIER DE LEVE OU D INVESTIGATIONS COMPLEMENTAIRES', '');
INSERT INTO l_doc_type VALUES ('SGC', 'DETAIL OU SCHEMA DE GENIE CIVIL', '');
INSERT INTO l_doc_type VALUES ('DPI', 'DOSSIER DE PIQUETAGE', '');
INSERT INTO l_doc_type VALUES ('DBL', 'DOSSIER DE RELEVE BOITES AUX LETTRES', '');
INSERT INTO l_doc_type VALUES ('KRV', 'RÈGLEMENT DE VOIRIE', '');
INSERT INTO l_doc_type VALUES ('CPV', 'PERMISSION OU AUTORISATION DE VOIRIE', '');
INSERT INTO l_doc_type VALUES ('DTT', 'DT EMISES DANS LE CADRE DU PROJET DE DEPLOIEMENT', '');
INSERT INTO l_doc_type VALUES ('DIT', 'DICT EMISES DANS LE CADRE DU PROJET DE DEPLOIEMENT', '');
INSERT INTO l_doc_type VALUES ('DAM', 'DIAGNOSTIC AMIANTE ENROBE', '');
INSERT INTO l_doc_type VALUES ('CIN', 'CONTRAT OU CONVENTION DE LOCATION/CESSION/ACHAT/OCCUPATION D INFRASTRUCTURE', '');
INSERT INTO l_doc_type VALUES ('CMU', 'CONTRAT OU CONVENTION DE CO-CONSTRUCTION OU MUTUALISATION DE TRAVAUX', '');
INSERT INTO l_doc_type VALUES ('DIP', 'DOSSIER D IMPLANTATION (SRO, NRO, BPI…)', '');
INSERT INTO l_doc_type VALUES ('SOP', 'SYNOPTIQUE OPTIQUE', '');
INSERT INTO l_doc_type VALUES ('SBP', 'PLAN DE BOITE, OU AUTRE ELEMENT DE BRANCHEMENT PASSIF', '');
INSERT INTO l_doc_type VALUES ('SRA', 'SCHEMA DE RACCORDEMENT (BAIE, ARMOIRE, REPARTITEUR…)', '');
INSERT INTO l_doc_type VALUES ('KEQ', 'DOCUMENTATION TECHNIQUE D EQUIPEMENT', '');
INSERT INTO l_doc_type VALUES ('CIM', 'CONVENTION THD IMMEUBLE', '');
INSERT INTO l_doc_type VALUES ('CIS', 'CONVENTION CADRE BAILLEUR SOCIAL', '');
INSERT INTO l_doc_type VALUES ('CDS', 'RÈGLEMENT DE SERVICE', '');
INSERT INTO l_doc_type VALUES ('COC', 'AUTRE CONVENTION D OCCUPATION EMPRISE PRIVEE', '');
INSERT INTO l_doc_type VALUES ('MRF', 'MESURE DE REFLECTOMETRIE', '');
INSERT INTO l_doc_type VALUES ('MFX', 'TEST D ETANCHEITE DE FOURREAUX ET/OU TESTS DE MANDRINAGE, AIGUILLAGE', '');
INSERT INTO l_doc_type VALUES ('RGC', 'PV DE RECEPTION GENIE CIVIL', '');
INSERT INTO l_doc_type VALUES ('DIF', 'DOSSIER INFRASTRUCTURE D ACCUEIL', '');
INSERT INTO l_doc_type VALUES ('DCB', 'DOSSIER DE CABLAGE', '');
INSERT INTO l_doc_type VALUES ('DOP', 'DOSSIER OPTIQUE', '');
INSERT INTO l_doc_type VALUES ('DPR', 'DOSSIER DE PROJET', '');
INSERT INTO l_doc_type VALUES ('DLG', 'DOSSIER DE LIVRABLES GRACETHD', '');
INSERT INTO l_doc_type VALUES ('DCI', 'DOSSIER DE COMMANDE POUR LOCATION/OCCUPATION D INFRASTRUCTURE', '');
INSERT INTO l_doc_type VALUES ('DCS', 'DOSSIER DE CREATION DE SITE', '');
INSERT INTO l_doc_type VALUES ('DRS', 'DOSSIER DE RACCORDEMENT DE SITE', '');
INSERT INTO l_doc_type VALUES ('KPL', 'PLAN LOCAL D URBANISME', '');
INSERT INTO l_doc_type VALUES ('RFR', 'FICHE DE RECETTE', '');
INSERT INTO l_doc_type VALUES ('RVR', 'PV DE RECEPTION DE VOIRIE', '');
INSERT INTO l_etat_type VALUES ('HS', 'A CHANGER', 'L infrastructure doit etre changee car la moindre intervention peut etre prejudiciable a la fourniture du service');
INSERT INTO l_etat_type VALUES ('ME', 'MAUVAIS ETAT', 'Mauvais etat general de l infrastructure qui ne permet pas certaines interventions');
INSERT INTO l_etat_type VALUES ('OK', 'BON ETAT', 'Bon etat general qui permet de realiser toute operation de maintenance, d exploitation ou d evolution');
INSERT INTO l_etat_type VALUES ('NC', 'NON CONCERNE', '');
INSERT INTO l_fo_color VALUES ('1', 'ROUGE (R)', '#FF0000');
INSERT INTO l_fo_color VALUES ('2', 'BLEU (BL)', '#0070C0');
INSERT INTO l_fo_color VALUES ('3', 'VERT (VE)', '#92D050');
INSERT INTO l_fo_color VALUES ('4', 'JAUNE (J)', '#FFFF00');
INSERT INTO l_fo_color VALUES ('5', 'VIOLET (V)', '#7638A3');
INSERT INTO l_fo_color VALUES ('6', 'BLANC (B)', '#FFFFFF');
INSERT INTO l_fo_color VALUES ('7', 'ORANGE (OR)', '#FFC000');
INSERT INTO l_fo_color VALUES ('8', 'GRIS (GR)', '#C1C1C1');
INSERT INTO l_fo_color VALUES ('9', 'MARRON (BR)', '#993300');
INSERT INTO l_fo_color VALUES ('10', 'NOIR (N)', '#000000');
INSERT INTO l_fo_color VALUES ('11', 'TURQUOISE (TU)', '#00B0F0');
INSERT INTO l_fo_color VALUES ('12', 'ROSE (RS)', '#FF65CC');
INSERT INTO l_fo_type VALUES ('G652', 'G652', '');
INSERT INTO l_fo_type VALUES ('G655', 'G655', '');
INSERT INTO l_fo_type VALUES ('G657', 'G657', '');
INSERT INTO l_geoloc_classe VALUES ('A', 'Classe de précision A', 'Décret du 15 février 2012 : un ouvrage ou tronçon d ouvrage est rangé dans la classe A si l incertitude maximale de localisation indiquée par son exploitant est inférieure ou égale à 40 cm et s il est rigide, ou à 50 cm s il est flexible. ');
INSERT INTO l_geoloc_classe VALUES ('AP', 'Classe de précision A, en planimétrie uniquement', 'Idem classe A, mais uniquement pour les valeurs x et y (hors z)');
INSERT INTO l_geoloc_classe VALUES ('B', 'Classe de précision B', 'Décret du 15 février 2012 : un ouvrage ou tronçon d ouvrage est rangé dans la classe B si l incertitude maximale de localisation indiquée par son exploitant est supérieure à celle relative à la classe A et inférieure ou égale à 1,5 mètre.');
INSERT INTO l_geoloc_classe VALUES ('C', 'Classe de précision C', 'Décret du 15 février 2012 : un ouvrage ou tronçon d ouvrage est rangé dans la classe C si l incertitude maximale de localisation indiquée par son exploitant est supérieure à 1,5 mètre, ou si son exploitant n est pas en mesure de fournir la localisation.');
INSERT INTO l_geoloc_mode VALUES ('LTRO', 'LEVE DURANT LA POSE', 'Objet positionne grace à un leve durant la phase travaux. Dans le cas de tranchee, ce leve a ete realise tranchee ouverte.');
INSERT INTO l_geoloc_mode VALUES ('LVIS', 'LEVE APRES LA POSE', 'Objet positionne grace a un leve. Dans le cas d une tranchee, uniquement les elements visibles ont ete leves (rustines sur le revetement, chambres encadrantes). Des cotations prises pendant la pose ont permis de completer ce lever.');
INSERT INTO l_geoloc_mode VALUES ('DETC', 'LEVE AVEC DETECTION', 'Un appareil de detection a ete utilise pour positionner les elements à lever.');
INSERT INTO l_geoloc_mode VALUES ('FDPL', 'COTATION PAR RAPPORT A UN LEVE DE GEOMETRE', 'Objet implante en reportant des cotations prises par rapport à un fond de plan precedemment leve.');
INSERT INTO l_geoloc_mode VALUES ('CBDU', 'COTATION PAR RAPPORT A UN FOND DE PLAN TIERS TYPE BDU', 'Objet implante en reportant des cotations prises par rapport au meilleur fond de plan actuellement disponible.');
INSERT INTO l_geoloc_mode VALUES ('CADA', 'POSITIONNEMENT SUR CADASTRE', 'Objet positionne par rapport aux planches cadastrales.');
INSERT INTO l_geoloc_mode VALUES ('ORTO', 'POSITIONNEMENT SUR ORTHOPHOTOGRAPHIE OU FOND DE PLAN CARTOGRAPHIQUE', 'Objet positionne par rapport à des orthophotos, ou des fonds cartographiques type RGE, FRANCE RASTER, OSM ou Bing');
INSERT INTO l_geoloc_mode VALUES ('INDT', 'INDETERMINE', '');
INSERT INTO l_immeuble_type VALUES ('P', 'PAVILLON', '');
INSERT INTO l_immeuble_type VALUES ('I', 'IMMEUBLE', '');
INSERT INTO l_implantation_type VALUES ('0', 'AERIEN TELECOM', '');
INSERT INTO l_implantation_type VALUES ('1', 'AERIEN ENERGIE', '');
INSERT INTO l_implantation_type VALUES ('2', 'FACADE', '');
INSERT INTO l_implantation_type VALUES ('3', 'IMMEUBLE', '');
INSERT INTO l_implantation_type VALUES ('4', 'PLEINE TERRE', '');
INSERT INTO l_implantation_type VALUES ('5', 'CANIVEAU', '');
INSERT INTO l_implantation_type VALUES ('6', 'GALERIE', '');
INSERT INTO l_implantation_type VALUES ('7', 'CONDUITE', '');
INSERT INTO l_implantation_type VALUES ('8', 'EGOUT', '');
INSERT INTO l_implantation_type VALUES ('9', 'SPECIFIQUE', '');
INSERT INTO l_infra_nature VALUES ('ASS', 'ASSAINISSEMENT', '');
INSERT INTO l_infra_nature VALUES ('EAU', 'EAU', '');
INSERT INTO l_infra_nature VALUES ('ELE', 'ELECTRICITE', '');
INSERT INTO l_infra_nature VALUES ('GAZ', 'GAZ', '');
INSERT INTO l_infra_nature VALUES ('NC', 'NON COMMUNIQUE', '');
INSERT INTO l_infra_nature VALUES ('TEL', 'TELECOM', '');
INSERT INTO l_infra_nature VALUES ('HTZ', 'HERZIEN', 'Faisceau hertzien. ');
INSERT INTO l_infra_type_log VALUES ('CX', 'COLLECTE TRANSPORT DISTRIBUTION', '');
INSERT INTO l_infra_type_log VALUES ('CO', 'COLLECTE', 'Liaison entre les PM');
INSERT INTO l_infra_type_log VALUES ('CT', 'COLLECTE TRANSPORT', '');
INSERT INTO l_infra_type_log VALUES ('CD', 'COLLECTE DISTRIBUTION', '');
INSERT INTO l_infra_type_log VALUES ('TD', 'TRANSPORT DISTRIBUTION', 'Mutualisation des fonctions transport et distribution');
INSERT INTO l_infra_type_log VALUES ('TR', 'TRANSPORT', '> 144Fo');
INSERT INTO l_infra_type_log VALUES ('DI', 'DISTRIBUTION', '<= 144Fo');
INSERT INTO l_infra_type_log VALUES ('RA', 'RACCORDEMENT FINAL', 'Entre le client et le point de branchement optique');
INSERT INTO l_infra_type_log VALUES ('BM', 'BOUCLE METROPOLITAINE', '');
INSERT INTO l_infra_type_log VALUES ('LH', 'LONGUE DISTANCE (LONG HAUL)', '');
INSERT INTO l_infra_type_log VALUES ('NC', 'NON COMMUNIQUE', '');
INSERT INTO l_masque_face VALUES ('A', 'A', '');
INSERT INTO l_masque_face VALUES ('B', 'B', '');
INSERT INTO l_masque_face VALUES ('C', 'C', '');
INSERT INTO l_masque_face VALUES ('D', 'D', '');
INSERT INTO l_masque_face VALUES ('E', 'E', '');
INSERT INTO l_masque_face VALUES ('F', 'F', '');
INSERT INTO l_masque_face VALUES ('G', 'G', '');
INSERT INTO l_masque_face VALUES ('H', 'H', '');
INSERT INTO l_masque_face VALUES ('I', 'I', '');
INSERT INTO l_masque_face VALUES ('J', 'J', '');
INSERT INTO l_noeud_type VALUES ('PT', 'POINT TECHNIQUE', '');
INSERT INTO l_noeud_type VALUES ('ST', 'SITE TECHNIQUE', '');
INSERT INTO l_noeud_type VALUES ('SF', 'SITE UTILISATEUR FINAL', '');
INSERT INTO l_noeud_type VALUES ('SE', 'SITE EMISSION', '');
INSERT INTO l_noeud_type VALUES ('SP', 'SPECIFIQUE', '');
INSERT INTO l_nro_type VALUES ('PON', 'NRO-PON', '');
INSERT INTO l_nro_type VALUES ('PTP', 'NRO-PTP', '');
INSERT INTO l_nro_type VALUES ('PON-PTP', 'NRO-PON-PTP', '');
INSERT INTO l_nro_etat VALUES ('PL', 'PLANIFIE', '');
INSERT INTO l_nro_etat VALUES ('EC', 'EN COURS DE DEPLOIEMENT', 'En cours d installation, sans qu une definition precise n ait ete partagee en Interop. ');
INSERT INTO l_nro_etat VALUES ('DP', 'DEPLOYE', 'Installe. Doit alors etre mis a disposition des operateurs ayant achete le PM. ');
INSERT INTO l_nro_etat VALUES ('AB', 'ABANDONNE', 'Le PM est abandonne. Cet etat doit apparaitre pendant 3 mois.');
INSERT INTO l_occupation_type VALUES ('0', 'VIDE', 'Infrastructure vide');
INSERT INTO l_occupation_type VALUES ('1.1', 'NON VIDE EXPLOITABLE', 'Infrastructure non vide mais exploitable car rangee');
INSERT INTO l_occupation_type VALUES ('1.2', 'NON VIDE NON EXPLOITABLE', 'Infrastructure non vide mais non exploitable car non rangee');
INSERT INTO l_occupation_type VALUES ('2', 'SATUREE', 'Infrastructure saturee');
INSERT INTO l_passage_type VALUES ('ACC', 'ACCOTEMENT', '');
INSERT INTO l_passage_type VALUES ('CHAU', 'CHAUSSEE', '');
INSERT INTO l_passage_type VALUES ('TROT', 'TROTTOIR', '');
INSERT INTO l_passage_type VALUES ('TER', 'TERRE', '');
INSERT INTO l_passage_type VALUES ('EMP', 'EMPIERRE', '');
INSERT INTO l_passage_type VALUES ('PON', 'PONT', '');
INSERT INTO l_passage_type VALUES ('SNC', 'PASSAGE SNCF', '');
INSERT INTO l_passage_type VALUES ('CAN', 'CANIVEAU TECHNIQUE', '');
INSERT INTO l_passage_type VALUES ('PAV', 'PAVES', '');
INSERT INTO l_passage_type VALUES ('NC', 'NON COMMUNIQUE', '');
INSERT INTO l_pose_type VALUES ('NC', 'NON COMMUNIQUE', '');
INSERT INTO l_pose_type VALUES ('TRA', 'TRADITIONNELLE', '');
INSERT INTO l_pose_type VALUES ('MEC', 'MECANISEE', '');
INSERT INTO l_pose_type VALUES ('MIC', 'MICRO TRANCHEE', '');
INSERT INTO l_pose_type VALUES ('FOR', 'FORAGE DIRIGE', '');
INSERT INTO l_pose_type VALUES ('ENS', 'ENSOUILLAGE', '');
INSERT INTO l_pose_type VALUES ('FON', 'FONÇAGE', '');
INSERT INTO l_pose_type VALUES ('ENC', 'ENCORBELLEMENT', '');
INSERT INTO l_pose_type VALUES ('STU', 'SOUS-TUBAGE', 'Sous-tubage infra existante');
INSERT INTO l_position_fonction VALUES ('CO', 'CONNECTEUR', '');
INSERT INTO l_position_fonction VALUES ('EP', 'EPISSURE', '');
INSERT INTO l_position_fonction VALUES ('PI', 'PIGTAIL', '');
INSERT INTO l_position_fonction VALUES ('AT', 'ATTENTE', '');
INSERT INTO l_position_fonction VALUES ('PA', 'PASSAGE', '');
INSERT INTO l_position_type VALUES ('CSA', 'CONNECTEUR SC-APC', '');
INSERT INTO l_position_type VALUES ('CSP', 'CONNECTEUR SC-PC', '');
INSERT INTO l_position_type VALUES ('CFA', 'CONNECTEUR FC-APC', '');
INSERT INTO l_position_type VALUES ('CFP', 'CONNECTEUR FC-PC', '');
INSERT INTO l_position_type VALUES ('SFU', 'SOUDURE FUSION', '');
INSERT INTO l_position_type VALUES ('SME', 'SOUDURE MECANIQUE', '');
INSERT INTO l_propriete_type VALUES ('CST', 'CONSTRUCTION', '');
INSERT INTO l_propriete_type VALUES ('RAC', 'RACHAT', '');
INSERT INTO l_propriete_type VALUES ('CES', 'CESSION', '');
INSERT INTO l_propriete_type VALUES ('IRU', 'IRU', '');
INSERT INTO l_propriete_type VALUES ('LOC', 'LOCATION', '');
INSERT INTO l_propriete_type VALUES ('OCC', 'OCCUPATION', 'Convention d occupation');
INSERT INTO l_ptech_nature VALUES ('A1', 'CHAMBRE A1', '');
INSERT INTO l_ptech_nature VALUES ('A2', 'CHAMBRE A2', '');
INSERT INTO l_ptech_nature VALUES ('A3', 'CHAMBRE A3', '');
INSERT INTO l_ptech_nature VALUES ('A4', 'CHAMBRE A4', '');
INSERT INTO l_ptech_nature VALUES ('B1', 'CHAMBRE B1', '');
INSERT INTO l_ptech_nature VALUES ('B2', 'CHAMBRE B2', '');
INSERT INTO l_ptech_nature VALUES ('B3', 'CHAMBRE B3', '');
INSERT INTO l_ptech_nature VALUES ('B4', 'CHAMBRE B4', '');
INSERT INTO l_ptech_nature VALUES ('C1', 'CHAMBRE C1', '');
INSERT INTO l_ptech_nature VALUES ('C2', 'CHAMBRE C2', '');
INSERT INTO l_ptech_nature VALUES ('C3', 'CHAMBRE C3', '');
INSERT INTO l_ptech_nature VALUES ('C4', 'CHAMBRE C4', '');
INSERT INTO l_ptech_nature VALUES ('D1', 'CHAMBRE D1', '');
INSERT INTO l_ptech_nature VALUES ('D2', 'CHAMBRE D2', '');
INSERT INTO l_ptech_nature VALUES ('D3', 'CHAMBRE D3', '');
INSERT INTO l_ptech_nature VALUES ('D4', 'CHAMBRE D4', '');
INSERT INTO l_ptech_nature VALUES ('E1', 'CHAMBRE E1', '');
INSERT INTO l_ptech_nature VALUES ('E2', 'CHAMBRE E2', '');
INSERT INTO l_ptech_nature VALUES ('E3', 'CHAMBRE E3', '');
INSERT INTO l_ptech_nature VALUES ('E4', 'CHAMBRE E4', '');
INSERT INTO l_ptech_nature VALUES ('J2C', 'CHAMBRE J2C', '');
INSERT INTO l_ptech_nature VALUES ('J2CR', 'CHAMBRE J2C REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('K1C', 'CHAMBRE K1C', '');
INSERT INTO l_ptech_nature VALUES ('K1CR', 'CHAMBRE K1C REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('K2C', 'CHAMBRE K2C', '');
INSERT INTO l_ptech_nature VALUES ('K2CR', 'CHAMBRE K2C REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('K3C', 'CHAMBRE K3C', '');
INSERT INTO l_ptech_nature VALUES ('K3CR', 'CHAMBRE K3C REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('L0T', 'CHAMBRE L0T', '');
INSERT INTO l_ptech_nature VALUES ('L0TR', 'CHAMBRE L0T REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('L1C', 'CHAMBRE L1C', '');
INSERT INTO l_ptech_nature VALUES ('L1T', 'CHAMBRE L1T', '');
INSERT INTO l_ptech_nature VALUES ('L1TR', 'CHAMBRE L1T REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('L2C', 'CHAMBRE L2C', '');
INSERT INTO l_ptech_nature VALUES ('L2T', 'CHAMBRE L2T', '');
INSERT INTO l_ptech_nature VALUES ('L2TR', 'CHAMBRE L2T REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('L3C', 'CHAMBRE L3C', '');
INSERT INTO l_ptech_nature VALUES ('L3T', 'CHAMBRE L3T', '');
INSERT INTO l_ptech_nature VALUES ('L3TR', 'CHAMBRE L3T REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('L4C', 'CHAMBRE L4C', '');
INSERT INTO l_ptech_nature VALUES ('L4T', 'CHAMBRE L4T', '');
INSERT INTO l_ptech_nature VALUES ('L4TR', 'CHAMBRE L4T REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('L5C', 'CHAMBRE L5C', '');
INSERT INTO l_ptech_nature VALUES ('L5T', 'CHAMBRE L5T', '');
INSERT INTO l_ptech_nature VALUES ('L5TR', 'CHAMBRE L5T REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('L6T', 'CHAMBRE L6T', '');
INSERT INTO l_ptech_nature VALUES ('L6TR', 'CHAMBRE L6T REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('M1C', 'CHAMBRE M1C', '');
INSERT INTO l_ptech_nature VALUES ('M1CR', 'CHAMBRE M1C REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('M2T', 'CHAMBRE M2T', '');
INSERT INTO l_ptech_nature VALUES ('M2TR', 'CHAMBRE M2T REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('M3C', 'CHAMBRE M3C', '');
INSERT INTO l_ptech_nature VALUES ('M3CR', 'CHAMBRE M3C REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('P1C', 'CHAMBRE P1C', '');
INSERT INTO l_ptech_nature VALUES ('P1CR', 'CHAMBRE P1C REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('P1T', 'CHAMBRE P1T', '');
INSERT INTO l_ptech_nature VALUES ('P1TR', 'CHAMBRE P1T REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('P2C', 'CHAMBRE P2C', '');
INSERT INTO l_ptech_nature VALUES ('P2CR', 'CHAMBRE P2C REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('P2T', 'CHAMBRE P2T', '');
INSERT INTO l_ptech_nature VALUES ('P2TR', 'CHAMBRE P2T REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('PBOI', 'POTEAU BOIS', '');
INSERT INTO l_ptech_nature VALUES ('PBET', 'POTEAU BETON', '');
INSERT INTO l_ptech_nature VALUES ('PMET', 'POTEAU METAL', '');
INSERT INTO l_ptech_nature VALUES ('PIND', 'POTEAU INDETERMINE', '');
INSERT INTO l_ptech_nature VALUES ('POTL', 'POTELET', '');
INSERT INTO l_ptech_nature VALUES ('R1T', 'CHAMBRE R1T', '');
INSERT INTO l_ptech_nature VALUES ('R2T', 'CHAMBRE R2T', '');
INSERT INTO l_ptech_nature VALUES ('R3T', 'CHAMBRE R3T', '');
INSERT INTO l_ptech_nature VALUES ('BOU', 'BOUCHON', '');
INSERT INTO l_ptech_nature VALUES ('REG', 'REGARD 30X30', '');
INSERT INTO l_ptech_nature VALUES ('OHN', 'OUVRAGE HORS NORMES', '');
INSERT INTO l_ptech_nature VALUES ('TRA', 'TRAVERSE', '');
INSERT INTO l_ptech_nature VALUES ('CRO', 'CROCHET', '');
INSERT INTO l_ptech_nature VALUES ('BAL', 'BALCON', '');
INSERT INTO l_ptech_nature VALUES ('FAI', 'FAITIERE', '');
INSERT INTO l_ptech_nature VALUES ('STR', 'SOUTERRAIN', '');
INSERT INTO l_ptech_nature VALUES ('SSO', 'SOUS-SOL', '');
INSERT INTO l_ptech_nature VALUES ('Y', 'SITE MANCHONNAGE Y', 'Fenêtre ouverture sur fourreaux existant pour mise en Y');
INSERT INTO l_ptech_nature VALUES ('IND', 'INDETERMINE', '');
INSERT INTO l_ptech_type_log VALUES ('T', 'TIRAGE', '');
INSERT INTO l_ptech_type_log VALUES ('R', 'RACCORDEMENT', '');
INSERT INTO l_ptech_type_phy VALUES ('A', 'APPUI', '');
INSERT INTO l_ptech_type_phy VALUES ('C', 'CHAMBRE', '');
INSERT INTO l_ptech_type_phy VALUES ('Z', 'AUTRE', '');
INSERT INTO l_qualite_info VALUES ('VA', 'VALIDE', '');
INSERT INTO l_qualite_info VALUES ('TH', 'THEORIQUE', '');
INSERT INTO l_qualite_info VALUES ('NC', 'NON COMMUNIQUE', '');
INSERT INTO l_reference_etat VALUES ('A', 'ACTIVE', '');
INSERT INTO l_reference_etat VALUES ('N', 'NON DISPONIBLE', '');
INSERT INTO l_reference_type VALUES ('BA', 'BAIE', '');
INSERT INTO l_reference_type VALUES ('BP', 'BPE', '');
INSERT INTO l_reference_type VALUES ('CA', 'CABLE', '');
INSERT INTO l_reference_type VALUES ('CS', 'CASSETTE', '');
INSERT INTO l_reference_type VALUES ('EQ', 'EQUIPEMENT', '');
INSERT INTO l_reference_type VALUES ('PT', 'POINT TECHNIQUE', '');
INSERT INTO l_reference_type VALUES ('TI', 'TIROIR', '');
INSERT INTO l_site_emission_type VALUES ('RADIO', 'RADIODIFFUSION', '');
INSERT INTO l_site_emission_type VALUES ('TEL', 'RADIO TELEPHONIE', '');
INSERT INTO l_site_emission_type VALUES ('BLR', 'BOUCLE LOCALE RADIO', '');
INSERT INTO l_site_emission_type VALUES ('FH', 'FAISCEAU HERTZIEN', '');
INSERT INTO l_site_emission_type VALUES ('WIFI', 'WIFI', '');
INSERT INTO l_site_emission_type VALUES ('WIMAX', 'WIMAX', '');
INSERT INTO l_site_type_log VALUES ('NRA', 'NŒUD RACCORDEMENT D ABONNES', '');
INSERT INTO l_site_type_log VALUES ('NRAHD', 'NŒUD RACCORDEMENT D ABONNES - HAUT DEBIT', '');
INSERT INTO l_site_type_log VALUES ('NRAMED', 'NŒUD RACCORDEMENT D ABONNES - MONTEE EN DEBIT', '');
INSERT INTO l_site_type_log VALUES ('NRAZO', 'NŒUD RACCORDEMENT D ABONNES - ZONE D OMBRE', '');
INSERT INTO l_site_type_log VALUES ('SRP', 'SOUS-REPARTITEUR CUIVRE PRIMAIRE', '');
INSERT INTO l_site_type_log VALUES ('SRS', 'SOUS-REPARTITEUR CUIVRE SECONDAIRE', '');
INSERT INTO l_site_type_log VALUES ('SRT', 'SOUS-REPARTITEUR CUIVRE TERTIAIRE', '');
INSERT INTO l_site_type_log VALUES ('NRO', 'NŒUD RACCORDEMENT OPTIQUE', '');
INSERT INTO l_site_type_log VALUES ('SRO', 'SOUS-REPARTITEUR OPTIQUE', '');
INSERT INTO l_site_type_log VALUES ('BRASSAGE', 'SITE DE BRASSAGE', 'Site non prevu pour heberger des equipements actifs (surtout longue distance)');
INSERT INTO l_site_type_log VALUES ('CLIENT', 'SITE CLIENT', 'Site entreprise ou administration qui n est pas un site utilisateur final (SUF). ');
INSERT INTO l_site_type_log VALUES ('HEBERG', 'SITE HEBERGEMENT', 'Site d hebergement d equipements actifs qui n est pas un NRO (hors architecture FTTH). ');
INSERT INTO l_site_type_phy VALUES ('ADR', 'ARMOIRE DE RUE', '');
INSERT INTO l_site_type_phy VALUES ('BAT', 'BATIMENT', '');
INSERT INTO l_site_type_phy VALUES ('SHE', 'SHELTER', '');
INSERT INTO l_sro_etat VALUES ('EC', 'EN COURS DE DEPLOIEMENT', 'En cours d installation, sans qu une definition precise n ait ete partagee en Interop. ');
INSERT INTO l_sro_etat VALUES ('DP', 'DEPLOYE', 'Installe. Doit alors etre mis a disposition des operateurs ayant achete le PM. ');
INSERT INTO l_sro_etat VALUES ('AB', 'ABANDONNE', 'Le PM est abandonne. Cet etat doit apparaitre pendant 3 mois.');
INSERT INTO l_sro_emplacement VALUES ('ADR', 'PME-ARMOIRE DE RUE', 'PM Exterieur au sens de la reglementation, contenu dans une armoire de rue. ');
INSERT INTO l_sro_emplacement VALUES ('SHE', 'PME-SHELTER', 'PM Exterieur au sens de la reglementation, contenu dans un shelter');
INSERT INTO l_sro_emplacement VALUES ('LTE', 'PME-LOCAL TECHNIQUE', 'PM Exterieur au sens de la reglementation, contenu dans un local technique, par exemple NRO. ');
INSERT INTO l_sro_emplacement VALUES ('PME', 'PM-EXTERIEUR', 'PM Exterieur au sens de la reglementation, dont l information du contenu n est pas disponible dans le SI de l OI. ');
INSERT INTO l_sro_emplacement VALUES ('PMI', 'PM-INTERIEUR', 'Situe dans une partie privative necessitant l accord d un tiers (syndic, gestionnaire) en plus de l accord de l OI. ');
INSERT INTO l_statut VALUES ('PRE', 'ETUDE PRELIMINAIRE', 'Resultat de l etude preliminaire, au sens du decret d application de la loi MOP (n°93-1268 du 29 nov. 1993) : premiere etude de faisabilite pour la construction d ouvrages neufs');
INSERT INTO l_statut VALUES ('DIA', 'ETUDE DE DIAGNOSTIC', 'Resultat de l etude de diagnostic, au sens du decret d application de la loi MOP (n°93-1268 du 29 nov. 1993) : pour une operation de reutilisation ou de rehabilitation d un ouvrage existant, etat des lieux, analyse technique, etudes complementaires');
INSERT INTO l_statut VALUES ('AVP', 'AVANT-PROJET', 'Resultat de l etude d avant-Projet, au sens du decret d application de la loi MOP (n°93-1268 du 29 nov. 1993) : confirmation de la faisabilite, premiere implantation de l ouvrage, autorisations administratives');
INSERT INTO l_statut VALUES ('PRO', 'PROJET', 'Resultat de l etude de projet, au sens du decret d application de la loi MOP (n°93-1268 du 29 nov. 1993) : precise les choix techniques, fixe l implantation topographique, les caracteristiques et le dimensionnement');
INSERT INTO l_statut VALUES ('ACT', 'PASSATION DES MARCHES DE TRAVAUX', 'Resultat de la mission d assistance a la passation des marches de travaux, au sens du decret d application de la loi MOP (n°93-1268 du 29 nov. 1993) : mise a jour eventuelle de l etude projet ');
INSERT INTO l_statut VALUES ('EXE', 'ETUDE D EXECUTION', 'Resultat de l etude d execution, au sens du decret d application de la loi MOP (n°93-1268 du 29 nov. 1993) : elaboration des documents a l usage du chantier. Le resultat de cette etude donne generalement lieu a un VISA du maître d oeuvre.');
INSERT INTO l_statut VALUES ('TVX', 'TRAVAUX', 'Resultat des missions de direction de l execution des travaux, d ordonnancement, de coordination et de pilotage ; ainsi que les operations prealables a la reception des travaux, au sens du decret d application de la loi MOP (n°93-1268 du 29 nov. 1993)');
INSERT INTO l_statut VALUES ('REC', 'RECOLEMENT', 'Resultat de la mission d assistance a la reception des travaux, au sens du decret d application de la loi MOP (n°93-1268 du 29 nov. 1993) : inclus le recolement des ouvrages et la realisation du Dossier des Ouvrages Executes');
INSERT INTO l_statut VALUES ('MCO', 'MAINTIENT EN CONDITIONS OPERATIONNELLES', 'Le statut MCO permet d identifier les objets qui font l objet d une operation de maintenance, avant le passage en statut REC une fois l operation achevee et son recolement realise');
INSERT INTO l_suf_racco VALUES ('AB', 'ABONNE', 'Logement dont l occupant a souscrit un abonnement a une offre d un operateur commercial sur un reseau en fibre optique jusqu a l abonne. ');
INSERT INTO l_suf_racco VALUES ('RA', 'RACCORDE', 'Logement pour lequel il existe une continuite entre le PM et la PTO. ');
INSERT INTO l_suf_racco VALUES ('RB', 'RACCORDABLE', 'Logement pour lequel il existe une continuite optique entre le PM et le PBO, ou entre le PM et la PTO si le PBO est absent. ');
INSERT INTO l_suf_racco VALUES ('EL', 'ELIGIBLE', 'Logement pour lequel au moins un operateur a relie le point de mutualisation a son NRO, et pour lequel il manque seulement le raccordement final et un eventuel  brassage au PM pour avoir une continuite optique entre le NRO et la PTO. ');
INSERT INTO l_suf_racco VALUES ('EM', 'ELIGIBLE MUTUALISE', 'Logement eligible pour lequel plusieurs operateurs ont relie le PM a leur NRO. ');
INSERT INTO l_suf_racco VALUES ('PR', 'PROGRAMME', 'Logement situe dans la zone arriere d un PM pour lequel le PM a ete installe et mis  a disposition des operateurs tiers, au sens de l annexe OO de la decision 2009-1106. ');
INSERT INTO l_suf_type VALUES ('R', 'RESIDENTIEL', '');
INSERT INTO l_suf_type VALUES ('P', 'PROFESSIONNEL', '');
INSERT INTO l_suf_type VALUES ('O', 'OPERATEUR', '');
INSERT INTO l_suf_type VALUES ('T', 'TECHNIQUE', '');
INSERT INTO l_technologie_type VALUES ('CUT', 'CUIVRE TELECOM', '');
INSERT INTO l_technologie_type VALUES ('OPT', 'OPTIQUE', '');
INSERT INTO l_technologie_type VALUES ('COA', 'COAXIAL', '');
INSERT INTO l_technologie_type VALUES ('ECL', 'ECLAIRAGE', '');
INSERT INTO l_technologie_type VALUES ('ELE', 'ELECTRICITE', '');
INSERT INTO l_technologie_type VALUES ('VID', 'VIDEO PROTECTION', '');
INSERT INTO l_technologie_type VALUES ('RAD', 'RADIO', '');
INSERT INTO l_tiroir_type VALUES ('TIROIR', 'TIROIR', '');
INSERT INTO l_tiroir_type VALUES ('TETE', 'TETE DE CABLE', '');
INSERT INTO l_tube VALUES ('1', 'SOUS FAISCEAU ROUGE UNE BAGUE COURTE', '');
INSERT INTO l_tube VALUES ('2', 'SOUS FAISCEAU BLEU DEUX BAGUES COURTES', '');
INSERT INTO l_tube VALUES ('3', 'SOUS FAISCEAU VERT TROIS BAGUES COURTES', '');
INSERT INTO l_tube VALUES ('4', 'SOUS FAISCEAU JAUNE QUATRE BAGUES COURTES', '');
INSERT INTO l_tube VALUES ('5', 'SOUS FAISCEAU VIOLET UNE BAGUE LONGUE', '');
INSERT INTO l_tube VALUES ('6', 'SOUS FAISCEAU BLANC UNE BAGUE LONGUE ET UNE BAGUE COURTE', '');
INSERT INTO l_zone_densite VALUES ('1', 'ZTD HAUTE DENSITE', '');
INSERT INTO l_zone_densite VALUES ('2', 'ZTD BASSE DENSITE', '');
INSERT INTO l_zone_densite VALUES ('3', 'ZMD', '');

COMMIT;
