DROP TABLE IF EXISTS t_tranchee;
DROP TABLE IF EXISTS t_artere;
DROP TABLE IF EXISTS t_fourreau;
DROP TABLE IF EXISTS t_cable;
DROP TABLE IF EXISTS t_fibre;
DROP TABLE IF EXISTS t_cassette;
DROP TABLE IF EXISTS t_position;
DROP TABLE IF EXISTS t_ropt;
DROP TABLE IF EXISTS t_noeud;
DROP TABLE IF EXISTS t_ptech;
DROP TABLE IF EXISTS t_masque;
DROP TABLE IF EXISTS t_love;
DROP TABLE IF EXISTS t_ebp;
DROP TABLE IF EXISTS t_sitetech;
DROP TABLE IF EXISTS t_ltech;
DROP TABLE IF EXISTS t_baie;
DROP TABLE IF EXISTS t_tiroir;
DROP TABLE IF EXISTS t_equipement;
DROP TABLE IF EXISTS t_reference;
DROP TABLE IF EXISTS t_suf;
DROP TABLE IF EXISTS t_adresse;
DROP TABLE IF EXISTS t_zone;
DROP TABLE IF EXISTS t_siteemission;
DROP TABLE IF EXISTS t_organisme;
DROP TABLE IF EXISTS t_document;


CREATE TABLE t_tranchee(	tr_id INTEGER   ,
	--GEOM Geometry(Linestring,2154) NOT NULL  ,
	tr_code VARCHAR(254) NOT NULL UNIQUE ,
	tr_codeext VARCHAR(254)   ,
	tr_ar_code VARCHAR(254)   REFERENCES t_artere(ar_code),
	tr_r1_code VARCHAR(100)   ,
	tr_r2_code VARCHAR(100)   ,
	tr_r3_code VARCHAR(100)   ,
	tr_r4_code VARCHAR(100)   ,
	tr_voie VARCHAR(254)   ,
	tr_mod_pos VARCHAR(254)   REFERENCES l_tranchee_pose_type(code),
	tr_long NUMERIC(8,2)   ,
	tr_lgreel NUMERIC(8,2)   ,
	tr_larg NUMERIC(4,2)   ,
	tr_typ_impl VARCHAR(254)   REFERENCES l_tranchee_implantation_type(code),
	tr_revet VARCHAR(254)   ,
	tr_remblai VARCHAR(254)   ,
	tr_charge NUMERIC(5,2)   ,
	tr_fildtec BOOLEAN   ,
	tr_gest_vo VARCHAR(20)   REFERENCES t_organisme (or_code),
	tr_pro_voi VARCHAR(20)   REFERENCES t_organisme (or_code),
	tr_dategc DATE   ,
	tr_mut_org VARCHAR(20)   REFERENCES t_organisme (or_code),
	tr_comment VARCHAR(254)   ,
	tr_statut VARCHAR(3)   REFERENCES l_statut (code),
	tr_etat VARCHAR(3)   REFERENCES l_etat_type (code),
	tr_amont VARCHAR(254)   ,
	tr_aval VARCHAR(254)   ,
	tr_qlt_geo VARCHAR(254)   ,
	tr_src_geo VARCHAR(254)   ,
	tr_creadat DATE   ,
	tr_majdate DATE   ,
	tr_majsrc VARCHAR(254)   ,
	tr_abddate DATE   ,
	tr_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_tranchee_pk" PRIMARY KEY (tr_id));	
	
CREATE TABLE t_artere(	ar_id INTEGER   ,
	--GEOM Geometry(Linestring,2154) NOT NULL  ,
	ar_code VARCHAR(254) NOT NULL UNIQUE ,
	ar_codeext VARCHAR(254)   ,
	ar_r1_code VARCHAR(100)   ,
	ar_r2_code VARCHAR(100)   ,
	ar_r3_code VARCHAR(100)   ,
	ar_r4_code VARCHAR(100)   ,
	ar_voie VARCHAR(254)   ,
	ar_typ_imp VARCHAR(2)   REFERENCES l_artere_implantation_type (code),
	ar_nature VARCHAR(3)   REFERENCES l_artere_nature (code),
	ar_typ_lgq VARCHAR(2) NOT NULL  REFERENCES l_artere_type (code),
	ar_etat VARCHAR(254)   REFERENCES l_etat_type (code),
	ar_long NUMERIC(8,2)   ,
	ar_lgreel NUMERIC(8,2)   ,
	ar_nbfour INTEGER   ,
	ar_nbdispo INTEGER   ,
	ar_noeud_a VARCHAR(254)   ,
	ar_noeud_b VARCHAR(254)   ,
	ar_comment VARCHAR(254)   ,
	ar_statut VARCHAR(254) NOT NULL  REFERENCES l_statut (code),
	ar_proptyp VARCHAR(3)   REFERENCES l_proptype(code),
	ar_avancmt VARCHAR(254)   ,
	ar_datems DATE   ,
	ar_qlt_geo VARCHAR(254)   ,
	ar_src_geo VARCHAR(254)   ,
	ar_creadat DATE   ,
	ar_majdate DATE   ,
	ar_majsrc VARCHAR(254)   ,
	ar_abddate DATE   ,
	ar_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_artere_pk" PRIMARY KEY (ar_id));	
	
CREATE TABLE t_fourreau(	fx_id INTEGER   ,
	fx_code VARCHAR(254) NOT NULL UNIQUE ,
	fx_codeext Varchar(254)   ,
	fx_etiquet VARCHAR(254)   ,
	fx_ar_code VARCHAR(254) NOT NULL  REFERENCES t_artere (ar_code),
	fx_fx_code VARCHAR(254)   REFERENCES t_fourreau (fx_code),
	fx_r1_code VARCHAR(100)   ,
	fx_r2_code VARCHAR(100)   ,
	fx_r3_code VARCHAR(100)   ,
	fx_r4_code VARCHAR(100)   ,
	fx_type VARCHAR(254) NOT NULL  REFERENCES l_fx_type (code),
	fx_etat VARCHAR(254)   REFERENCES l_etat_type (code),
	fx_numseri VARCHAR(254)   ,
	fx_dia_int INTEGER   ,
	fx_dia_ext INTEGER   ,
	fx_color VARCHAR(254)   ,
	fx_long NUMERIC(8,2)   ,
	fx_nbcable INTEGER   ,
	fx_occup VARCHAR(254)   REFERENCES l_occupation_type (code),
	fx_dateins Date   ,
	fx_dateaig Date   ,
	fx_dateman Date   ,
	fx_prop VARCHAR(20)   REFERENCES t_organisme (or_code),
	fx_gest VARCHAR(20)   REFERENCES t_organisme (or_code),
	fx_user VARCHAR(20)   REFERENCES t_organisme (or_code),
	fx_comment VARCHAR(254)   ,
	fx_creadat DATE   ,
	fx_majdate DATE   ,
	fx_majsrc VARCHAR(254)   ,
	fx_abddate DATE   ,
	fx_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_fourreau_pk" PRIMARY KEY (fx_id));	
	
CREATE TABLE t_masque(	mq_id INTEGER NOT NULL  ,
	mq_nd_code VARCHAR(254) NOT NULL  REFERENCES t_noeud (nd_code),
	mq_face VARCHAR(1) NOT NULL  REFERENCES l_masque_face (code),
	mq_col INTEGER NOT NULL  ,
	mq_ligne INTEGER NOT NULL  ,
	mq_fx_code VARCHAR(254)   REFERENCES t_fourreau (fx_code),
	mq_cb_code VARCHAR(254)   REFERENCES t_cable (cb_code),
	mq_qualinf VARCHAR(3)   REFERENCES l_qualite_info(code),
	mq_creadat DATE   ,
	mq_majdate DATE   ,
	mq_majsrc VARCHAR(254)   ,
	mq_abddate DATE   ,
	mq_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_masque_pk" PRIMARY KEY (mq_id));	
	
CREATE TABLE t_cable(	cb_id INTEGER   ,
	--GEOM Geometry(Linestring,2154) NOT NULL  ,
	cb_code VARCHAR(254) NOT NULL UNIQUE ,
	cb_codeext VARCHAR(254)   ,
	cb_etiquet VARCHAR(254)   ,
	cb_ar_code VARCHAR(254)   REFERENCES t_artere (ar_code),
	cb_fx_code VARCHAR(254)   REFERENCES t_fourreau (fx_code),
	cb_bp_amon VARCHAR(254) NOT NULL  ,
	cb_bp_aval VARCHAR(254) NOT NULL  ,
	cb_r1_code VARCHAR(100)   ,
	cb_r2_code VARCHAR(100)   ,
	cb_r3_code VARCHAR(100)   ,
	cb_r4_code VARCHAR(100)   ,
	cb_long NUMERIC   ,
	cb_lgreel NUMERIC   ,
	cb_tech VARCHAR(3) NOT NULL  REFERENCES l_technologie_type (code),
	cb_ref INTEGER   REFERENCES t_reference (rf_id),
	cb_capafo INTEGER   ,
	cb_fo_disp INTEGER   ,
	cb_modulo INTEGER   ,
	cb_diam NUMERIC NOT NULL  ,
	cb_color VARCHAR(254)   ,
	cb_prop VARCHAR(254)   REFERENCES t_organisme (or_code),
	cb_gest VARCHAR(254)   REFERENCES t_organisme (or_code),
	cb_util VARCHAR(254)   REFERENCES t_organisme (or_code),
	cb_datepos DATE   ,
	cb_statut VARCHAR(254) NOT NULL  REFERENCES l_statut (code),
	cb_etat VARCHAR(3)   REFERENCES l_etat (code),
	cb_comment VARCHAR(254)   ,
	cb_qlt_geo VARCHAR(254)   ,
	cb_src_geo VARCHAR(254)   ,
	cb_creadat DATE   ,
	cb_majdate DATE   ,
	cb_majsrc VARCHAR(254)   ,
	cb_abddate DATE   ,
	cb_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_cable_pk" PRIMARY KEY (cb_id));	
	
CREATE TABLE t_love(	lo_id INTEGER NOT NULL  ,
	lo_cb_code INTEGER NOT NULL  REFERENCES t_cable (cb_code),
	lo_nd_code INTEGER NOT NULL  REFERENCES t_noeud (nd_code),
	lo_long INTEGER   ,
	lo_creadat DATE   ,
	lo_majdate DATE   ,
	lo_majsrc VARCHAR(254)   ,
	lo_abddate DATE   ,
	lo_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_love_pk" PRIMARY KEY (lo_id));	
	
CREATE TABLE t_fibre(	fo_id INTEGER   ,
	fo_code VARCHAR(254) NOT NULL UNIQUE ,
	fo_code_ext VARCHAR(254)   ,
	fo_ca_code VARCHAR(254) NOT NULL  REFERENCES t_cable (ca_code),
	fo_nincab INTEGER   ,
	fo_numtub INTEGER   ,
	fo_nintub INTEGER   ,
	fo_etat VARCHAR(2)   REFERENCES l_fibre_etat (code),
	fo_color VARCHAR(7)   REFERENCES l_fo_color(code),
	fo_reper VARCHAR(5)   REFERENCES l_tube (tube_id),
	fo_ropt VARCHAR(100)   ,
	fo_creadat DATE   ,
	fo_majdate date   ,
	fo_majsrc VARCHAR(254)   ,
	fo_abddate DATE   ,
	fo_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_fibre_pk" PRIMARY KEY (fo_id));	
	
CREATE TABLE t_position(	po_id INTEGER   ,
	po_numero INTEGER   ,
	po_fonct VARCHAR(3)   REFERENCES l_position_fonction (code),
	po_amont INTEGER   REFERENCES t_fibre (fo_id),
	po_aval INTEGER   REFERENCES t_fibre (fo_id),
	po_ca_id INTEGER   REFERENCES t_cassette (cs_id),
	po_ti_code VARCHAR(254)   REFERENCES t_tiroir (ti_code),
	po_type VARCHAR(10)   REFERENCES l_position_type (code),
	po_etat VARCHAR(2)   REFERENCES l_position_etat (code),
	po_preaff VARCHAR(50)   ,
	po_creadat DATE   ,
	po_majdate DATE   ,
	po_majsrc VARCHAR(254)   ,
	po_abddate DATE   ,
	po_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_position_pk" PRIMARY KEY (po_id));	
	
CREATE TABLE t_ropt(	ro_id INTEGER   ,
	ro_code VARCHAR(254) NOT NULL  ,
	ro_code_ext VARCHAR(254)   ,
	ro_fo_id INTEGER   REFERENCES t_fibre (fo_id),
	ro_creadat DATE   ,
	ro_majdate DATE   ,
	ro_majsrc VARCHAR(254)   ,
	ro_abddate DATE   ,
	ro_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_ropt_pk" PRIMARY KEY (ro_id));	
	
CREATE TABLE t_noeud(	nd_id INTEGER   ,
	--GEOM Geometry(Point,2154) NOT NULL  ,
	nd_code VARCHAR(254) NOT NULL UNIQUE ,
	nd_codeext VARCHAR(254)   ,
	nd_nom VARCHAR(254)   ,
	nd_coderat VARCHAR(254)   REFERENCES t_noeud (nd_code),
	nd_r1_code VARCHAR(100)   ,
	nd_r2_code VARCHAR(100)   ,
	nd_r3_code VARCHAR(100)   ,
	nd_r4_code VARCHAR(100)   ,
	nd_voie VARCHAR(254)   ,
	nd_c_insee VARCHAR(6)   ,
	nd_type VARCHAR(254)   ,
	nd_etat VARCHAR(254)   REFERENCES l_etat_type (code),
	nd_occp VARCHAR(254)   REFERENCES l_occupation_type (code),
	nd_access VARCHAR(10)   REFERENCES l_accessibilite_type (code),
	nd_haut NUMERIC   ,
	nd_detection VARCHAR(254)   ,
	nd_type_ep VARCHAR (10)   REFERENCES l_technologie_type (code),
	nd_dateins DATE   ,
	nd_pro VARCHAR(20)   REFERENCES t_organisme (or_code),
	nd_gest VARCHAR(20)   REFERENCES t_organisme (or_code),
	nd_user VARCHAR(254)   REFERENCES t_organisme (or_code),
	nd_comment VARCHAR(254)   ,
	nd_statut VARCHAR(254) NOT NULL  REFERENCES l_statut (code),
	nd_datems Date   ,
	nd_qltgeol VARCHAR(254)   ,
	nd_srcgeol VARCHAR(254)   ,
	nd_creadat DATE   ,
	nd_majdate DATE   ,
	nd_majsrc VARCHAR(254)   ,
	nd_abddate DATE   ,
	nd_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_noeud_pk" PRIMARY KEY (nd_id));	
	
CREATE TABLE t_ptech(	pt_id INTEGER   ,
	pt_code VARCHAR(254) NOT NULL UNIQUE ,
	pt_codeext Varchar(254)   ,
	pt_etiquet VARCHAR(254)   ,
	pt_nd_code VARCHAR(254) NOT NULL  ,
	pt_usage VARCHAR(1) NOT NULL  REFERENCES l_ptech_usage_type (code),
	pt_type VARCHAR(20) NOT NULL  REFERENCES l_ptech_type (code),
	pt_secu BOOLEAN   ,
	pt_lignes INTEGER   ,
	pt_a_dan NUMERIC   ,
	pt_a_dtetu Date   ,
	pt_a_struc VARCHAR(100)   ,
	pt_a_strat BOOLEAN   ,
	pt_a_passa BOOLEAN   ,
	pt_rotatio NUMERIC(5,2)   ,
	pt_creadat DATE   ,
	pt_majdate DATE   ,
	pt_majsrc VARCHAR(254)   ,
	pt_abddate DATE   ,
	pt_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_ptech_pk" PRIMARY KEY (pt_id));	
	
CREATE TABLE t_ebp(	bp_id INTEGER   ,
	bp_code VARCHAR(254) NOT NULL UNIQUE ,
	bp_etiquet VARCHAR(254)   ,
	bp_codeext VARCHAR(254)   ,
	bp_pt_code VARCHAR(254) NOT NULL  ,
	bp_voie VARCHAR(254)   ,
	bp_type VARCHAR(10) NOT NULL  REFERENCES l_bp_type (code),
	bp_etat VARCHAR(3)    REFERENCES l_etat_type (code),
	bp_typephy VARCHAR(254)   ,
	bp_occup VARCHAR(10)   REFERENCES l_occupation_type (code),
	bp_dateins DATE   ,
	bp_prop VARCHAR(20)   REFERENCES t_organisme (or_code),
	bp_gest VARCHAR(20)   REFERENCES t_organisme (or_code),
	bp_util VARCHAR(20)   REFERENCES t_organisme (or_code),
	bp_pm_code VARCHAR(254)   REFERENCES t_site(st_code),
	bp_suf VARCHAR(50)   REFERENCES t_suf(sf_code),
	bp_comment VARCHAR(254)   ,
	bp_entrees INTEGER   ,
	bp_creadat DATE   ,
	bp_majdate DATE   ,
	bp_majsrc VARCHAR(254)   ,
	bp_abddate DATE   ,
	bp_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_ebp_pk" PRIMARY KEY (bp_id));	
	
CREATE TABLE t_cassette(	cs_id INTEGER   ,
	cs_nb_pas NUMERIC   ,
	cs_bp_code VARCHAR(254) NOT NULL  REFERENCES t_ebp (bp_code),
	cs_num NUMERIC   ,
	cs_type VARCHAR(10)   REFERENCES l_cassette_type (code),
	cs_face VARCHAR(20)   ,
	cs_ref INTEGER   ,
	cs_creadat DATE   ,
	cs_majdate DATE   ,
	cs_majsrc VARCHAR(254)   ,
	cs_abddate DATE   ,
	cs_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_cassette_pk" PRIMARY KEY (cs_id));	
	
CREATE TABLE t_suf(	sf_id INTEGER   ,
	sf_code VARCHAR(50)  UNIQUE ,
	sf_oper VARCHAR(20) NOT NULL  REFERENCES t_organisme (or_code),
	st_code VARCHAR(254)   REFERENCES t_sitetech (st_code),
	sf_nom VARCHAR (30)   ,
	sf_type VARCHAR(1) NOT NULL  REFERENCES l_suf_type (code),
	sf_tbati VARCHAR(1) NOT NULL  REFERENCES l_type_bati (code),
	sf_ad_id INTEGER   REFERENCES t_adresse (ad_id),
	sf_pr_nom VARCHAR (30)   ,
	sf_pr_tel VARCHAR (20)   ,
	sf_pr_mail VARCHAR (30)   ,
	sf_pr_adr VARCHAR (254)   ,
	sf_resid VARCHAR (100)   ,
	sf_local VARCHAR (100)   ,
	sf_nb_pr INTEGER   ,
	sf_proxi VARCHAR(1)   ,
	sf_gest VARCHAR(25)   ,
	sf_nat VARCHAR(1)   ,
	sf_adduc VARCHAR(3)   ,
	sf_racc VARCHAR(1)   ,
	sf_prio VARCHAR(1)   ,
	sf_comment VARCHAR(254)   ,
	sf_nbprise INTEGER   ,
	sf_src_geo VARCHAR(254)   ,
	sf_qlt_geo VARCHAR(254)   ,
	sf_creadat DATE   ,
	sf_majdate DATE   ,
	sf_majsrc VARCHAR(254)   ,
	sf_abddate DATE   ,
	sf_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_suf_pk" PRIMARY KEY (sf_id));	
	
CREATE TABLE t_adresse(	ad_id INTEGER   ,
	ad_ville VARCHAR (254)   ,
	ad_postal INTEGER   ,
	ad_insee INTEGER   ,
	ad_rivoli VARCHAR (254)   ,
	ad_num INTEGER   ,
	ad_cpmt VARCHAR (3)   ,
	ad_type VARCHAR (10)   REFERENCES l_adress_etat(code),
	ad_libel VARCHAR (254)   ,
	ad_id_ban VARCHAR (254)   ,
	ad_hexacl VARCHAR (254)   ,
	ad_bati VARCHAR (20)   ,
	ad_escal VARCHAR (20)   ,
	ad_etage VARCHAR (20)   ,
	ad_observ VARCHAR (254)   ,
	ad_etat INTEGER   ,
	ad_autr01 VARCHAR (254)   ,
	ad_autr02 VARCHAR (254)   ,
	ad_autr03 VARCHAR (254)   ,
	ad_autr04 VARCHAR (254)   ,
	ad_autr05 VARCHAR (254)   ,
	ad_autr06 VARCHAR (254)   ,
	ad_creadat DATE   ,
	ad_majdate DATE   ,
	ad_majsrc VARCHAR(254)   ,
	ad_abddate DATE   ,
	ad_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_adresse_pk" PRIMARY KEY (ad_id));	
	
CREATE TABLE t_sitetech(	st_id INTEGER   ,
	st_code VARCHAR(254) NOT NULL UNIQUE ,
	st_nd_code VARCHAR(254) NOT NULL  ,
	st_codeext Varchar(254)   ,
	st_nom VARCHAR (254)   ,
	st_type INTEGER NOT NULL  ,
	st_nbpr INTEGER   ,
	st_adres VARCHAR(254)   ,
	st_cp VARCHAR(254)   ,
	st_ville VARCHAR(254)   ,
	st_prop VARCHAR(20)   REFERENCES t_organisme (or_code),
	st_gest VARCHAR(20)   REFERENCES t_organisme (or_code),
	st_dt_ms DATE   ,
	st_etat VARCHAR(3) NOT NULL  REFERENCES l_etat_type (code),
	st_stat VARCHAR(3) NOT NULL  REFERENCES l_statut (code),
	st_creadat DATE   ,
	st_majdate DATE   ,
	st_majsrc VARCHAR(254)   ,
	st_abddate DATE   ,
	st_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_sitetech_pk" PRIMARY KEY (st_id));	
	
CREATE TABLE t_ltech(	lt_id INTEGER NOT NULL  ,
	lt_code VARCHAR(254) NOT NULL UNIQUE ,
	lt_codeext VARCHAR(254)   ,
	lt_st_code VARCHAR(254) NOT NULL  REFERENCES t_sitetech (st_code),
	lt_nom VARCHAR(20)   ,
	lt_local VARCHAR (254)   ,
	lt_prop VARCHAR(20)   REFERENCES t_organisme (or_code),
	lt_gest VARCHAR(20)   REFERENCES t_organisme (or_code),
	lt_dt_ms DATE   ,
	lt_etat VARCHAR(3) NOT NULL  REFERENCES l_etat_type (code),
	lt_stat VARCHAR(3) NOT NULL  REFERENCES l_statut (code),
	lt_creadat DATE   ,
	lt_majdate DATE   ,
	lt_majsrc VARCHAR(254)   ,
	lt_abddate DATE   ,
	lt_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_ltech_pk" PRIMARY KEY (lt_id));	
	
CREATE TABLE t_baie(	ba_id INTEGER NOT NULL  ,
	ba_code VARCHAR(254) NOT NULL UNIQUE ,
	ba_codeext VARCHAR(254)   ,
	ba_etiquet VARCHAR(254)   ,
	ba_lt_code VARCHAR(254) NOT NULL  REFERENCES t_ltech (lt_code),
	ba_nom VARCHAR(20)   ,
	ba_nb_u NUMERIC   ,
	ba_haut NUMERIC   ,
	ba_larg NUMERIC   ,
	ba_prof NUMERIC   ,
	ba_prop VARCHAR(20)   REFERENCES t_organisme (or_code),
	ba_gest VARCHAR(20)   REFERENCES t_organisme (or_code),
	ba_etat VARCHAR(3)   REFERENCES l_etat_type (code),
	ba_stat VARCHAR(3)   REFERENCES l_statut (code),
	ba_ref INTEGER   REFERENCES reference (rf_id),
	ba_type VARCHAR(10)   REFERENCES l_baie_type (code),
	ba_creadat DATE   ,
	ba_majdate DATE   ,
	ba_majsrc VARCHAR(254)   ,
	ba_abddate DATE   ,
	ba_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_baie_pk" PRIMARY KEY (ba_id));	
	
CREATE TABLE t_tiroir(	ti_id INTEGER NOT NULL  ,
	ti_code VARCHAR(254) NOT NULL UNIQUE ,
	ti_codeext VARCHAR(254)   ,
	ti_etiquet VARCHAR(254)   ,
	ti_ba_code VARCHAR(254) NOT NULL  REFERENCES t_baie (ba_code),
	ti_local VARCHAR(254)   ,
	ti_placem NUMERIC   ,
	ti_taille NUMERIC   ,
	ti_prop VARCHAR(20)   REFERENCES t_organisme (or_code),
	ti_ref INTEGER   REFERENCES t_reference (rf_id),
	ti_etat VARCHAR(3)   REFERENCES l_etat (code),
	ti_type VARCHAR(10)   REFERENCES l_tiroir_type (code),
	ti_creadat DATE   ,
	ti_majdate DATE   ,
	ti_majsrc VARCHAR(254)   ,
	ti_abddate DATE   ,
	ti_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_tiroir_pk" PRIMARY KEY (ti_id));	
	
CREATE TABLE t_equipement(	eq_id INTEGER NOT NULL  ,
	eq_code VARCHAR(254) NOT NULL UNIQUE ,
	eq_codeext VARCHAR(254)   ,
	eq_etiquet VARCHAR(254)   ,
	eq_ti_code VARCHAR(254) NOT NULL  ,
	eq_objet VARCHAR(254) NOT NULL  REFERENCES t_baie (ba_code),
	eq_nom VARCHAR(20)   ,
	eq_prop VARCHAR(20)   REFERENCES t_organisme (or_code),
	eq_dt_ps DATE   ,
	eq_creadat DATE   ,
	eq_majdate DATE   ,
	eq_majsrc VARCHAR(254)   ,
	eq_abddate DATE   ,
	eq_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_equipement_pk" PRIMARY KEY (eq_id));	
	
CREATE TABLE t_reference(	rf_id INTEGER NOT NULL  ,
	rf_type VARCHAR(2)   REFERENCES l_reference_type (code),
	rf_fabric VARCHAR(20)   REFERENCES t_organisme (or_code),
	rf_design VARCHAR(254)   ,
	rf_etat VARCHAR(2)   REFERENCES l_reference_etat (code),
	rf_creadat DATE   ,
	rf_majdate DATE   ,
	rf_majsrc VARCHAR(254)   ,
	rf_abddate DATE   ,
	rf_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_reference_pk" PRIMARY KEY (rf_id));	
	
CREATE TABLE t_siteemission(	se_id INTEGER NOT NULL  ,
	se_anfr VARCHAR(50) NOT NULL  ,
	se_nd_code VARCHAR(50)   REFERENCES t_noeud (nd_code),
	se_type VARCHAR(254) NOT NULL  REFERENCES l_site_emission_type (code),
	se_creadat DATE   ,
	se_majdate DATE   ,
	se_majsrc VARCHAR(254)   ,
	se_abddate DATE   ,
	se_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_siteemission_pk" PRIMARY KEY (se_id));	
	
CREATE TABLE t_zone(	zo_id INTEGER   ,
	--GEOM MultiPolygon   ,
	zo_code VARCHAR(254)  UNIQUE ,
	zo_nd_code VARCHAR(254) NOT NULL  REFERENCES t_noeud (nd_code),
	zo_zo_code VARCHAR(254)   REFERENCES t_zone (zo_code),
	zo_type VARCHAR(254) NOT NULL  REFERENCES l_zo_type(code),
	zo_r1_code VARCHAR(100)   ,
	zo_r2_code VARCHAR(100)   ,
	zo_r3_code VARCHAR(100)   ,
	zo_r4_code VARCHAR(100)   ,
	zo_etat VARCHAR(3)   REFERENCES l_etat_type (code),
	zo_statut VARCHAR(3)   REFERENCES l_statut (code),
	zo_creadat DATE   ,
	zo_majdate DATE   ,
	zo_majsrc VARCHAR(254)   ,
	zo_abddate DATE   ,
	zo_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_zone_PK" PRIMARY KEY (zo_id));	
	
CREATE TABLE t_organisme(	or_code VARCHAR (20) NOT NULL  ,
	or_siren VARCHAR(9)   ,
	or_nom VARCHAR(254) NOT NULL  ,
	or_type VARCHAR(254)   ,
	or_l331 VARCHAR(254)   ,
	or_siret VARCHAR(254)   ,
	or_nometab VARCHAR(254)   ,
	or_adresse VARCHAR(254)   ,
	or_telfixe VARCHAR(254)   ,
	or_mail VARCHAR(254)   ,
	or_creadat DATE   ,
	or_majdate DATE   ,
	or_majsrc VARCHAR(254)   ,
	or_abddate DATE   ,
	or_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_organisme_pk" PRIMARY KEY (or_code));	
	
CREATE TABLE t_document(	do_id INTEGER NOT NULL  ,
	do_code VARCHAR(254)   ,
	do_codeext VARCHAR(254)   ,
	do_tbltype VARCHAR(10)   REFERENCES l_doc_tab (code),
	do_codeobj INTEGER   ,
	do_budg VARCHAR(50)   ,
	do_creadat DATE   ,
	do_majdate DATE   ,
	do_majsrc VARCHAR(254)   ,
	do_abddate DATE   ,
	do_abdsrc VARCHAR(254)   ,
CONSTRAINT "t_document_pk" PRIMARY KEY (do_id));	


CREATE INDEX IF NOT EXISTS tr_code_idx ON t_tranchee(tr_code);
CREATE INDEX IF NOT EXISTS tr_ar_code_idx ON t_tranchee(tr_ar_code);
CREATE INDEX IF NOT EXISTS tr_gest_vo_idx ON t_tranchee(tr_gest_vo);
CREATE INDEX IF NOT EXISTS tr_pro_voi_idx ON t_tranchee(tr_pro_voi);
CREATE INDEX IF NOT EXISTS tr_statut_idx ON t_tranchee(tr_statut);
CREATE INDEX IF NOT EXISTS tr_etat_idx ON t_tranchee(tr_etat);
CREATE INDEX IF NOT EXISTS tr_amont_idx ON t_tranchee(tr_amont);
CREATE INDEX IF NOT EXISTS tr_aval_idx ON t_tranchee(tr_aval);
DROP INDEX IF EXISTS mq_alveole_idx; CREATE UNIQUE INDEX mq_alveole_idx ON t_masque (mq_nd_code, mq_face, mq_col, mq_ligne);
DROP INDEX IF EXISTS lo_cb_nd_code_idx; CREATE UNIQUE INDEX lo_cb_nd_code_idx ON t_love (lo_cb_code, lo_nd_code) ;
CREATE INDEX IF NOT EXISTS cs_bp_code_idx ON t_cassette(cs_bp_code);
CREATE INDEX IF NOT EXISTS cs_type_idx ON t_cassette(cs_type);
CREATE INDEX IF NOT EXISTS cs_ref_idx ON t_cassette(cs_ref);
