BEGIN;
INSERT INTO l_accessibilite_type VALUES ('Restreint', 'Verrouillee', '');
INSERT INTO l_accessibilite_type VALUES ('Libre', 'Non verrouillée', '');
INSERT INTO l_adress_etat VALUES ('EXI', 'EXISTANTE', '');
INSERT INTO l_adress_etat VALUES ('CRE', 'A CREER', '');
INSERT INTO l_adress_etat VALUES ('ASU', 'A SUPPRIMER', '');
INSERT INTO l_adress_etat VALUES ('SUP', 'SUPPRIMEE', '');
INSERT INTO l_adress_type VALUES ('R', 'RUE', '');
INSERT INTO l_adress_type VALUES ('AV', 'AVENUE', '');
INSERT INTO l_adress_type VALUES ('IMP', 'IMPASSE', '');
INSERT INTO l_adress_type VALUES ('CHE', 'CHEMIN', '');
INSERT INTO l_adress_type VALUES ('BD', 'BOULEVARD', '');
INSERT INTO l_adress_type VALUES ('RTE', 'ROUTE', '');
INSERT INTO l_adress_type VALUES ('LOT', 'LOTISSEMENT', '');
INSERT INTO l_adress_type VALUES ('CH', 'CHAUSSEE', '');
INSERT INTO l_adress_type VALUES ('VOIE', 'VOIE', '');
INSERT INTO l_adress_type VALUES ('COURS', 'COURS', '');
INSERT INTO l_adress_type VALUES ('ALL', 'ALLEE', '');
INSERT INTO l_adress_type VALUES ('CLOS', 'CLOS', '');
INSERT INTO l_adress_type VALUES ('MTE', 'MONTEE', '');
INSERT INTO l_adress_type VALUES ('HAM', 'HAMEAU', '');
INSERT INTO l_adress_type VALUES ('PL', 'PLACE', '');
INSERT INTO l_adress_type VALUES ('TRA', 'TRAVERSEE', '');
INSERT INTO l_adress_type VALUES ('PAS', 'PASSAGE', '');
INSERT INTO l_adress_type VALUES ('GAL', 'GALERIE', '');
INSERT INTO l_adress_type VALUES ('VIA', 'VIA', '');
INSERT INTO l_artere_implantation_type VALUES ('0', 'AERIEN ORANGE', '');
INSERT INTO l_artere_implantation_type VALUES ('1', 'AERIEN EDF', '');
INSERT INTO l_artere_implantation_type VALUES ('2', 'FACADE', '');
INSERT INTO l_artere_implantation_type VALUES ('3', 'IMMEUBLE', '');
INSERT INTO l_artere_implantation_type VALUES ('4', 'PLEINE TERRE', '');
INSERT INTO l_artere_implantation_type VALUES ('5', 'CANIVEAU', '');
INSERT INTO l_artere_implantation_type VALUES ('6', 'GALERIE', '');
INSERT INTO l_artere_implantation_type VALUES ('7', 'CONDUITE', '');
INSERT INTO l_artere_implantation_type VALUES ('8', 'EGOUT', '');
INSERT INTO l_artere_nature VALUES ('ASS', 'ASSAINISSEMENT', '');
INSERT INTO l_artere_nature VALUES ('EAU', 'EAU', '');
INSERT INTO l_artere_nature VALUES ('ELE', 'ELECTRICITÉ', '');
INSERT INTO l_artere_nature VALUES ('GAZ', 'GAZ', '');
INSERT INTO l_artere_nature VALUES ('NC', 'NC', '');
INSERT INTO l_artere_nature VALUES ('TEL', 'TÉLÉCOM', '');
INSERT INTO l_artere_type VALUES ('CO', 'COLLECTE', 'Liaison entre les PM');
INSERT INTO l_artere_type VALUES ('TR', 'TRANSPORT', '> 144Fo');
INSERT INTO l_artere_type VALUES ('DI', 'DISTRIBUTION', '<= 144Fo');
INSERT INTO l_artere_type VALUES ('AD', 'ADDUCTION', 'Entre le client et la distribution');
INSERT INTO l_artere_type VALUES ('BM', 'BOUCLE METROPOLITAINE', '');
INSERT INTO l_artere_type VALUES ('LH', 'LONGUE DISTANCE (LONG HAUL)', '');
INSERT INTO l_baie_type VALUES ('BAIE', 'BAIE', '');
INSERT INTO l_baie_type VALUES ('FERME', 'FERME', '');
INSERT INTO l_bp_localisation VALUES ('SITE', 'SITE', '');
INSERT INTO l_bp_localisation VALUES ('AERIEN', 'AUTRE AERIEN', '');
INSERT INTO l_bp_localisation VALUES ('CHAMBRE', 'CHAMBRE', '');
INSERT INTO l_bp_racco VALUES ('CLI001', '', '');
INSERT INTO l_bp_racco VALUES ('CLI002', 'CLIENT INJOIGNABLE IMPOSSIBLE DE PRENDRE RDV', '');
INSERT INTO l_bp_racco VALUES ('CLI003', '', '');
INSERT INTO l_bp_racco VALUES ('CLI004', '', '');
INSERT INTO l_bp_racco VALUES ('CLI005', 'CLIENT REFUS CLIENT', '');
INSERT INTO l_bp_racco VALUES ('CLI006', 'CLIENT REFUS GESTIONNAIRE D IMMEUBLES', '');
INSERT INTO l_bp_racco VALUES ('CLI007', 'CLIENT ABSENCE CLIENT LORS DE L INTERVENTION', '');
INSERT INTO l_bp_racco VALUES ('ADR001', '', '');
INSERT INTO l_bp_racco VALUES ('ADR002', '', '');
INSERT INTO l_bp_racco VALUES ('ADR003', '', '');
INSERT INTO l_bp_racco VALUES ('ADR004', '', '');
INSERT INTO l_bp_racco VALUES ('ADR005', '', '');
INSERT INTO l_bp_racco VALUES ('ADR006', '', '');
INSERT INTO l_bp_racco VALUES ('IMP001', '', '');
INSERT INTO l_bp_racco VALUES ('IMP002', 'PB OU PM SATURE', '');
INSERT INTO l_bp_racco VALUES ('IMP003', '', '');
INSERT INTO l_bp_racco VALUES ('IMP004', 'COMMANDE IMPOSSIBLE :  IDENTIFIANT INTERNE OC INCONNUE', '');
INSERT INTO l_bp_racco VALUES ('IMP005', 'FORMAT ERRONE', '');
INSERT INTO l_bp_racco VALUES ('IMP006', 'CHAMPS OBLIGATOIRES MANQUANTS', '');
INSERT INTO l_bp_racco VALUES ('INTER001', 'HL OI : HOTLINE OI INJOIGNABLE', '');
INSERT INTO l_bp_racco VALUES ('INTER002', 'ABSENCE DE CONTINUITE OPTIQUE', '');
INSERT INTO l_bp_racco VALUES ('INTER003', 'AFFAIBLISSEMENT TROP IMPORTANT', '');
INSERT INTO l_bp_racco VALUES ('AUT001', 'AUTRE MOTIF : COMMENTAIRES LIBRES', '');
INSERT INTO l_bp_racco VALUES ('RDV01', 'NOMBRE DE MODIFICATIONS MAX DEPASSE', '');
INSERT INTO l_bp_racco VALUES ('RDV02', '', '');
INSERT INTO l_bp_racco VALUES ('RDV03', 'COMMANDE GELEE', '');
INSERT INTO l_bp_racco VALUES ('RACOK', 'PRISE RACCORDEE', '');
INSERT INTO l_bp_type VALUES ('BDO', 'BDO', '');
INSERT INTO l_bp_type VALUES ('DROIT', 'Joint droit', '');
INSERT INTO l_bp_type VALUES ('DERIV', 'Joint de dérivation', '');
INSERT INTO l_bp_type VALUES ('PC', 'PC', '');
INSERT INTO l_bp_type VALUES ('BPE', 'BPE', '');
INSERT INTO l_bp_type VALUES ('PTO', 'PTO', '');
INSERT INTO l_cable_type VALUES ('CABLE', 'CABLE', '');
INSERT INTO l_cable_type VALUES ('JARRETIERE', 'JARRETIERE', '');
INSERT INTO l_cassette_type VALUES ('PLATEAU', 'PLATEAU DE LOVAGE BPE', '');
INSERT INTO l_cassette_type VALUES ('EPISSURE', 'EPISSURE', '');
INSERT INTO l_cassette_type VALUES ('SPLITTER', 'SPLITTER', '');
INSERT INTO l_cassette_type VALUES ('CONNECTEUR', 'CONNECTEUR', '');
INSERT INTO l_clim_type VALUES ('SANS', 'SANS', '');
INSERT INTO l_clim_type VALUES ('VENTIL', 'VENTILLATION', '');
INSERT INTO l_clim_type VALUES ('CLIM', 'CLIMATISATION', '');
INSERT INTO l_color VALUES ('1', '#ff0000', 'rouge (R)');
INSERT INTO l_color VALUES ('2', '#0070c0', 'bleu (BL)');
INSERT INTO l_color VALUES ('3', '#92d050', 'vert (VE)');
INSERT INTO l_color VALUES ('4', '#ffff00', 'jaune (J)');
INSERT INTO l_color VALUES ('5', '#7638a3', 'violet (V)');
INSERT INTO l_color VALUES ('6', '#ffffff', 'blanc (B)');
INSERT INTO l_color VALUES ('7', '#ffc000', 'orange (OR)');
INSERT INTO l_color VALUES ('8', '#c1c1c1', 'gris (GR)');
INSERT INTO l_color VALUES ('9', '#993300', 'marron (BR)');
INSERT INTO l_color VALUES ('10', '#000000', 'noir (N)');
INSERT INTO l_color VALUES ('11', '#00b0f0', 'turquoise (TU)');
INSERT INTO l_color VALUES ('12', '#ff65cc', 'rose (RS)');
INSERT INTO l_connexion_type VALUES ('FO', 'Fibre optique', '');
INSERT INTO l_connexion_type VALUES ('CU', 'Cuivre', '');
INSERT INTO l_connexion_type VALUES ('CO', 'Coaxial', '');
INSERT INTO l_connexion_type VALUES ('FH', 'Faisceau hertzien', '');
INSERT INTO l_doc_tab VALUES ('CB', 'CABLE', '');
INSERT INTO l_doc_tab VALUES ('FX', 'FOURREAU', '');
INSERT INTO l_doc_tab VALUES ('BP', 'ELEMENT BRANCHEMENT PASSIF', '');
INSERT INTO l_doc_tab VALUES ('MQ', 'MASQUE', '');
INSERT INTO l_doc_tab VALUES ('NO', 'NOEUD', '');
INSERT INTO l_doc_tab VALUES ('TR', 'TRANCHEE', '');
INSERT INTO l_doc_tab VALUES ('PTO', 'POINT TECHNIQUE', '');
INSERT INTO l_doc_tab VALUES ('ST', 'SITE TECHNIQUE', '');
INSERT INTO l_doc_tab VALUES ('SF', 'SITEUTILISATEUR FINAL', '');
INSERT INTO l_doc_tab VALUES ('LT', 'LOCAL TECHNIQUE', '');
INSERT INTO l_doc_tab VALUES ('AD', 'ADRESSE', '');
INSERT INTO l_doc_tab VALUES ('BAD', 'BAIE', '');
INSERT INTO l_doc_tab VALUES ('CST', 'CASSETTE', '');
INSERT INTO l_doc_tab VALUES ('EQ', 'EQUIPEMENT', '');
INSERT INTO l_doc_tab VALUES ('TI', 'TIROIR', '');
INSERT INTO l_doc_tab VALUES ('OR', 'ORGANISME', '');
INSERT INTO l_etat_type VALUES ('EXI', 'EXISTANT', '');
INSERT INTO l_etat_type VALUES ('CRE', 'A CREER', '');
INSERT INTO l_etat_type VALUES ('CHG', 'A CHANGER', 'L''infrastructure doit être changée car la moindre intervention peut être préjudiciable à la fourniture du service');
INSERT INTO l_etat_type VALUES ('BAD', 'MAUVAIS ETAT', 'Mauvais état général de l''infrastructure qui ne permet pas certaines interventions');
INSERT INTO l_etat_type VALUES ('BON', 'BON ETAT', 'Bon état général qui permet de réaliser toute opération de maintenance, d''exploitation ou d''''évolution');
INSERT INTO l_fibre_etat VALUES ('HS', 'HS', '');
INSERT INTO l_fibre_etat VALUES ('OK', 'FONCTIONNELLE', '');
INSERT INTO l_fx_nature VALUES ('PEHD', 'PEHD', '');
INSERT INTO l_fx_nature VALUES ('PVC', 'PVC', '');
INSERT INTO l_fx_nature VALUES ('AUTRE', 'AUTRE', '');
INSERT INTO l_fx_type VALUES ('AUTRE', 'Autre', '');
INSERT INTO l_fx_type VALUES ('CUC', 'Conduite Unitaire Ciment', '');
INSERT INTO l_fx_type VALUES ('NC', 'Non communiqué', '');
INSERT INTO l_fx_type VALUES ('PEHD', 'PEHD', '');
INSERT INTO l_fx_type VALUES ('PVC', 'PVC', '');
INSERT INTO l_fx_type VALUES ('TPC', 'TPC', '');
INSERT INTO l_lgau_type VALUES ('CHAMBRE', 'CHAMBRE', '');
INSERT INTO l_lgau_type VALUES ('AERIEN', 'AERIEN', '');
INSERT INTO l_lgau_type VALUES ('FACADE', 'FACADE', '');
INSERT INTO l_lgau_type VALUES ('SPECIFIQUE', 'SPECIFIQUE', '');
INSERT INTO l_lgau_type VALUES ('EGOUT', 'EGOUT', '');
INSERT INTO l_lgau_type VALUES ('ENCORBELLEMENT', 'ENCORBELLEMENT', '');
INSERT INTO l_masque_face VALUES ('A', 'A', '');
INSERT INTO l_masque_face VALUES ('B', 'B', '');
INSERT INTO l_masque_face VALUES ('C', 'C', '');
INSERT INTO l_masque_face VALUES ('D', 'D', '');
INSERT INTO l_masque_face VALUES ('E', 'E', '');
INSERT INTO l_masque_face VALUES ('F', 'F', '');
INSERT INTO l_masque_face VALUES ('G', 'G', '');
INSERT INTO l_masque_face VALUES ('H', 'H', '');
INSERT INTO l_masque_face VALUES ('I', 'I', '');
INSERT INTO l_masque_face VALUES ('J', 'J', '');
INSERT INTO l_noeud_type VALUES ('P', 'PHYSIQUE', '');
INSERT INTO l_noeud_type VALUES ('S', 'SPECIFIQUE', '');
INSERT INTO l_occupation_type VALUES ('0', 'Vide', 'Infrastructure vide');
INSERT INTO l_occupation_type VALUES ('1.1', 'Non vide exploitable', 'Infrastructure non vide mais exploitable car rangée');
INSERT INTO l_occupation_type VALUES ('1.2', 'Non vide non exploitable', 'Infrastructure non vide mais non exploitable car non rangée');
INSERT INTO l_occupation_type VALUES ('2', 'Saturée', 'Infrastructure saturée');
INSERT INTO l_position_etat VALUES ('HS', 'HORS-SERVICE', '');
INSERT INTO l_position_etat VALUES ('ES', 'EN FONCTION', '');
INSERT INTO l_position_etat VALUES ('VE', 'A VERIFIER', '');
INSERT INTO l_position_fonction VALUES ('CON', 'CONNECTEUR', '');
INSERT INTO l_position_fonction VALUES ('EPI', 'EPISSURE', '');
INSERT INTO l_position_fonction VALUES ('PIG', 'PIGTAIL', '');
INSERT INTO l_position_fonction VALUES ('ATT', 'ATTENTE', '');
INSERT INTO l_position_fonction VALUES ('PAS', 'PASSAGE', '');
INSERT INTO l_position_fonction VALUES ('JCD', 'EPISSURE-JCD', '');
INSERT INTO l_position_fonction VALUES ('HDS', 'EPISSURE-HDS', '');
INSERT INTO l_position_type VALUES ('SC', 'SC', 'CONNECTEUR');
INSERT INTO l_position_type VALUES ('EC', 'EC', 'CONNECTEUR');
INSERT INTO l_position_type VALUES ('FC', 'FC', 'CONNECTEUR');
INSERT INTO l_position_type VALUES ('FUSION', 'FUSION', 'SOUDURE');
INSERT INTO l_position_type VALUES ('MECANIQUE', 'MECANIQUE', 'SOUDURE');
INSERT INTO l_position_type VALUES ('LC', 'LC', 'CONNECTEUR');
INSERT INTO l_position_type VALUES ('ST', 'ST', 'CONNECTEUR');
INSERT INTO l_position_type VALUES ('SCAPC', 'SCAPC', 'CONNECTEUR');
INSERT INTO l_propriete_type VALUES ('CST', 'CONSTRUCTION', '');
INSERT INTO l_propriete_type VALUES ('RAC', 'RACHAT', '');
INSERT INTO l_propriete_type VALUES ('CES', 'CESSION', '');
INSERT INTO l_propriete_type VALUES ('IRU', 'IRU', '');
INSERT INTO l_propriete_type VALUES ('LOC', 'LOCATION', '');
INSERT INTO l_ptech_type VALUES ('J2C', 'J2C', '');
INSERT INTO l_ptech_type VALUES ('J2CR', 'J2CR', '');
INSERT INTO l_ptech_type VALUES ('K1C', 'K1C', '');
INSERT INTO l_ptech_type VALUES ('K1CR', 'K1CR', '');
INSERT INTO l_ptech_type VALUES ('K2C', 'K2C', '');
INSERT INTO l_ptech_type VALUES ('K2CR', 'K2CR', '');
INSERT INTO l_ptech_type VALUES ('K3C', 'K3C', '');
INSERT INTO l_ptech_type VALUES ('K3CR', 'K3CR', '');
INSERT INTO l_ptech_type VALUES ('L0T', 'L0T', '');
INSERT INTO l_ptech_type VALUES ('L0TR', 'L0TR', '');
INSERT INTO l_ptech_type VALUES ('L1T', 'L1T', '');
INSERT INTO l_ptech_type VALUES ('L1TR', 'L1TR', '');
INSERT INTO l_ptech_type VALUES ('L2T', 'L2T', '');
INSERT INTO l_ptech_type VALUES ('L2TR', 'L2TR', '');
INSERT INTO l_ptech_type VALUES ('L3T', 'L3T', '');
INSERT INTO l_ptech_type VALUES ('L3TR', 'L3TR', '');
INSERT INTO l_ptech_type VALUES ('L4T', 'L4T', '');
INSERT INTO l_ptech_type VALUES ('L4TR', 'L4TR', '');
INSERT INTO l_ptech_type VALUES ('L5T', 'L5T', '');
INSERT INTO l_ptech_type VALUES ('L5TR', 'L5TR', '');
INSERT INTO l_ptech_type VALUES ('L6T', 'L6T', '');
INSERT INTO l_ptech_type VALUES ('L6TR', 'L6TR', '');
INSERT INTO l_ptech_type VALUES ('M1C', 'M1C', '');
INSERT INTO l_ptech_type VALUES ('M1CR', 'M1CR', '');
INSERT INTO l_ptech_type VALUES ('M2T', 'M2T', '');
INSERT INTO l_ptech_type VALUES ('M2TR', 'M2TR', '');
INSERT INTO l_ptech_type VALUES ('M3C', 'M3C', '');
INSERT INTO l_ptech_type VALUES ('M3CR', 'M3CR', '');
INSERT INTO l_ptech_type VALUES ('P1C', 'P1C', '');
INSERT INTO l_ptech_type VALUES ('P1CR', 'P1CR', '');
INSERT INTO l_ptech_type VALUES ('P2C', 'P2C', '');
INSERT INTO l_ptech_type VALUES ('P2CR', 'P2CR', '');
INSERT INTO l_ptech_type VALUES ('P2T', 'P2T', '');
INSERT INTO l_ptech_type VALUES ('P2TR', 'P2TR', '');
INSERT INTO l_ptech_type VALUES ('PBOIS', 'Poteau bois', '');
INSERT INTO l_ptech_type VALUES ('PBETON', 'Poteau béton', '');
INSERT INTO l_ptech_type VALUES ('PMETAL', 'Poteau métal', '');
INSERT INTO l_ptech_type VALUES ('BOUCHON', 'Bouchon', '');
INSERT INTO l_ptech_type VALUES ('REGARD', 'Regard', '');
INSERT INTO l_ptech_type VALUES ('INDETERMINE', 'Indéterminé', '');
INSERT INTO l_ptech_type VALUES ('L1C', 'L1C', '');
INSERT INTO l_ptech_type VALUES ('L2C', 'L2C', '');
INSERT INTO l_ptech_type VALUES ('L3C', 'L3C', '');
INSERT INTO l_ptech_type VALUES ('L4C', 'L4C', '');
INSERT INTO l_ptech_type VALUES ('L5C', 'L5C', '');
INSERT INTO l_ptech_type VALUES ('OHN', 'Ouvrage Hors Normes', '');
INSERT INTO l_ptech_type VALUES ('P1T', 'P1T', '');
INSERT INTO l_ptech_type VALUES ('TRAVERSE', 'TRAVERSE', '');
INSERT INTO l_ptech_type VALUES ('CROCHET', 'CROCHET', '');
INSERT INTO l_ptech_type VALUES ('BALCON', 'BALCON', '');
INSERT INTO l_ptech_type VALUES ('FAITIERE', 'FAITIERE', '');
INSERT INTO l_ptech_usage_type VALUES ('T', 'TIRAGE', '');
INSERT INTO l_ptech_usage_type VALUES ('R', 'RACCORDEMENT', '');
INSERT INTO l_qualitegeolocalisation VALUES ('1', 'Topologie traditionnelle ou GPS centimétrique', 'Précision < 10cm');
INSERT INTO l_qualitegeolocalisation VALUES ('2', 'GPS submétrique', 'Précision < 1m');
INSERT INTO l_qualitegeolocalisation VALUES ('3', 'GPS métrique', 'Précision > 1m');
INSERT INTO l_qualitegeolocalisation VALUES ('4', 'Numérisation sur orthophotographie', 'Précision (3 à 5 m)');
INSERT INTO l_qualitegeolocalisation VALUES ('5', 'GPS grand public', 'Précision faible > 5 m');
INSERT INTO l_reference_etat VALUES ('A', 'ACTIVE', '');
INSERT INTO l_reference_etat VALUES ('N', 'NON DISPONIBLE', '');
INSERT INTO l_reference_type VALUES ('CA', 'CABLE', '');
INSERT INTO l_reference_type VALUES ('CS', 'CASSETTE', '');
INSERT INTO l_reference_type VALUES ('BP', 'BPE', '');
INSERT INTO l_reference_type VALUES ('TI', 'TIROIR', '');
INSERT INTO l_reference_type VALUES ('BA', 'BAIE', '');
INSERT INTO l_site_emission_type VALUES ('RADIO', 'RadioDiffusion', '');
INSERT INTO l_site_emission_type VALUES ('TEL', 'Radio Téléphonie', '');
INSERT INTO l_site_emission_type VALUES ('BLR', 'Boucle locale Radio', '');
INSERT INTO l_site_emission_type VALUES ('FH', 'Faisceau Hertzien', '');
INSERT INTO l_site_emission_type VALUES ('WIFI', 'Wifi', '');
INSERT INTO l_site_emission_type VALUES ('WIMAX', 'Wimax', '');
INSERT INTO l_site_type VALUES ('NRA', 'NŒUD RACCORDEMENT D''ABONNÉS', '');
INSERT INTO l_site_type VALUES ('NRAHD', 'NŒUD RACCORDEMENT D''ABONNÉS - HAUT DÉBIT', '');
INSERT INTO l_site_type VALUES ('NRAMED', 'NŒUD RACCORDEMENT D''ABONNÉS - MONTÉE EN DÉBIT', '');
INSERT INTO l_site_type VALUES ('NRAZO', 'NŒUD RACCORDEMENT D''ABONNÉS - ZONE D''OMBRE', '');
INSERT INTO l_site_type VALUES ('SRP', 'SOUS-REPARTITEUR CUIVRE PRIMAIRE', '');
INSERT INTO l_site_type VALUES ('SRS', 'SOUS-REPARTITEUR CUIVRE SECONDAIRE', '');
INSERT INTO l_site_type VALUES ('SRT', 'SOUS-REPARTITEUR CUIVRE TERTIAIRE', '');
INSERT INTO l_site_type VALUES ('NRO', 'NŒUD RACCORDEMENT OPTIQUE', '');
INSERT INTO l_site_type VALUES ('SRO', 'SOUS-REPARTITEUR OPTIQUE', '');
INSERT INTO l_site_type VALUES ('BRASSAGE', 'SITE DE BRASSAGE', 'Site non prévu pour héberger des équipements actifs (surtout longue distance)');
INSERT INTO l_site_type VALUES ('CLIENT', 'SITE CLIENT', 'Site entreprise ou administration qui n''est pas un site utilisateur final (SUF). ');
INSERT INTO l_site_type VALUES ('HEBERG', 'SITE HEBERGEMENT', 'Site d''hébergement d''équipements actifs qui n''est pas un NRO (hors architecture FTTH). ');
INSERT INTO l_site_type_structurel VALUES ('ADR', 'ARMOIRE DE RUE', '');
INSERT INTO l_site_type_structurel VALUES ('BAT', 'BATIMENT', '');
INSERT INTO l_site_type_structurel VALUES ('SHE', 'SHELTER', '');
INSERT INTO l_statut VALUES ('SDI', 'SCHEMA INGENIERIE', '');
INSERT INTO l_statut VALUES ('APS', 'APS', '');
INSERT INTO l_statut VALUES ('APD', 'APD', '');
INSERT INTO l_statut VALUES ('PRE', 'PRE', '');
INSERT INTO l_statut VALUES ('DOE', 'DOE', '');
INSERT INTO l_suf_type VALUES ('R', 'RESIDENTIEL', '');
INSERT INTO l_suf_type VALUES ('P', 'PROFESSIONNEL', '');
INSERT INTO l_suf_type VALUES ('O', 'OPERATEUR', '');
INSERT INTO l_suf_type VALUES ('T', 'TECHNIQUE', '');
INSERT INTO l_suf_type VALUES ('S', 'SDS', '');
INSERT INTO l_suf_type VALUES ('C', 'SSC', '');
INSERT INTO l_technologie_cable_type VALUES ('CU', 'CUIVRE', '');
INSERT INTO l_technologie_cable_type VALUES ('FO', 'FIBRE OPTIQUE', '');
INSERT INTO l_technologie_cable_type VALUES ('CO', 'COAXIAL', '');
INSERT INTO l_technologie_type VALUES ('CUT', 'CUIVRE TÉLÉCOM', '');
INSERT INTO l_technologie_type VALUES ('OPT', 'OPTIQUE', '');
INSERT INTO l_technologie_type VALUES ('COAX', 'COAXIAL', '');
INSERT INTO l_technologie_type VALUES ('ECL', 'ECLAIRAGE', '');
INSERT INTO l_technologie_type VALUES ('ELEC', 'ELECTRICITÉ', '');
INSERT INTO l_tiroir_type VALUES ('TIROIR', 'TIROIR', '');
INSERT INTO l_tiroir_type VALUES ('TETE', 'TETE DE CABLE', '');
INSERT INTO l_tranchee_implantation_type VALUES ('ACC', 'ACCOTEMENT', '');
INSERT INTO l_tranchee_implantation_type VALUES ('CHAU', 'CHAUSSÉE', '');
INSERT INTO l_tranchee_implantation_type VALUES ('TROT', 'TROTTOIR', '');
INSERT INTO l_tranchee_implantation_type VALUES ('TER', 'TERRE', '');
INSERT INTO l_tranchee_implantation_type VALUES ('EMP', 'EMPIERRE', '');
INSERT INTO l_tranchee_implantation_type VALUES ('PON', 'PONT', '');
INSERT INTO l_tranchee_implantation_type VALUES ('SNC', 'PASSAGE SNCF', '');
INSERT INTO l_tranchee_implantation_type VALUES ('CAN', 'CANIVEAU TECHNIQUE', '');
INSERT INTO l_tranchee_implantation_type VALUES ('PAV', 'PAVÉS', '');
INSERT INTO l_tranchee_implantation_type VALUES ('NC', 'NON COMMUNIQUÉ', '');
INSERT INTO l_tranchee_pose_type VALUES ('NC', 'NON COMMUNIQUÉ', '');
INSERT INTO l_tranchee_pose_type VALUES ('TRA', 'TRADITIONNELLE', '');
INSERT INTO l_tranchee_pose_type VALUES ('MEC', 'MÉCANISÉE', '');
INSERT INTO l_tranchee_pose_type VALUES ('MIC', 'MICRO TRANCHÉE', '');
INSERT INTO l_tranchee_pose_type VALUES ('FOR', 'FORAGE DIRIGÉ', '');
INSERT INTO l_tranchee_pose_type VALUES ('ENS', 'ENSOUILLAGE', '');
INSERT INTO l_tranchee_pose_type VALUES ('FON', 'FONÇAGE', '');
INSERT INTO l_tranchee_pose_type VALUES ('ENC', 'ENCORBELLEMENT', '');
INSERT INTO l_tranchee_pose_type VALUES ('STU', 'SOUS-TUBAGE', 'Sous-tubage infra existante');
INSERT INTO l_tranchee_type VALUES ('1', 'ACCOTEMENT NON REVETU', 'TRANCHEE MECANISEE MINI');
INSERT INTO l_tranchee_type VALUES ('2', 'ACCOTEMENT NON REVETU', 'TRANCHEE MECANISEE MINI');
INSERT INTO l_tranchee_type VALUES ('3', 'ACCOTEMENT NON REVETU', 'TRANCHEE MECANISEE MINI');
INSERT INTO l_tranchee_type VALUES ('4', 'ACCOTEMENT NON REVETU', 'TRANCHEE MECANISEE MICRO-RIVE');
INSERT INTO l_tranchee_type VALUES ('5', 'TROTTOIR OU ACCOTEMENT REVETU', 'TRANCHEE TRADITIONNELLE');
INSERT INTO l_tranchee_type VALUES ('6', 'TROTTOIR OU ACCOTEMENT REVETU', 'TRANCHEE MECANISEE MINI-MICRO');
INSERT INTO l_tranchee_type VALUES ('7', 'CHAUSSEE T3/T4/T5', 'TRANCHEE MECANISEE MINI');
INSERT INTO l_tranchee_type VALUES ('8', 'CHAUSSEE T3/T4/T5', 'TRANCHEE MECANISEE MICRO');
INSERT INTO l_tranchee_type VALUES ('9', 'CHAUSSEE T1/T2', 'TRANCHEE MECANISEE MINI');
INSERT INTO l_tranchee_type VALUES ('10', 'CHAUSSEE T1/T2', 'TRANCHEE MECANISEE MICRO');
INSERT INTO l_tranchee_type VALUES ('11', 'CHAUSSEE T1/T2', 'TRANCHEE TRADITIONNELLE');
INSERT INTO l_tranchee_type VALUES ('12', 'CHAUSSEE T3', 'TRANCHEE TRADITIONNELLE');
INSERT INTO l_tranchee_type VALUES ('13', 'CHAUSSEE T4/T5', 'TRANCHEE TRADITIONNELLE');
INSERT INTO l_tranchee_type VALUES ('14', 'CHEMIN EMPIERRE', 'TRANCHEE TRADITIONNELLE');
INSERT INTO l_tranchee_type VALUES ('15', 'CHEMIN EMPIERRE', 'TRANCHEE MECANISEE MINI-MICRO');
INSERT INTO l_tranchee_type VALUES ('16', 'ESPACE VERT', 'TRANCHEE TRADITIONNELLE');
INSERT INTO l_tube VALUES ('1', 'SOUS FAISCEAU ROUGE UNE BAGUE COURTE', '');
INSERT INTO l_tube VALUES ('2', 'SOUS FAISCEAU BLEU DEUX BAGUES COURTES', '');
INSERT INTO l_tube VALUES ('3', 'SOUS FAISCEAU VERT TROIS BAGUES COURTES', '');
INSERT INTO l_tube VALUES ('4', 'SOUS FAISCEAU JAUNE QUATRE BAGUES COURTES', '');
INSERT INTO l_tube VALUES ('5', 'SOUS FAISCEAU VIOLET UNE BAGUE LONGUE', '');
INSERT INTO l_tube VALUES ('6', 'SOUS FAISCEAU BLANC UNE BAGUE LONGUE ET UNE BAGUE COURTE', '');
INSERT INTO l_type_bati VALUES ('1', 'MONO-SITE', '');
INSERT INTO l_type_bati VALUES ('2', 'MULTI-SITE', '');
INSERT INTO l_zd_type VALUES ('NC', 'NON COMMUNIQUÉ', '');
INSERT INTO l_zd_type VALUES ('ZANRO', 'ZONE ARRIERE NOEUD DE RACCARODEMENT OPTIQUE', '');
INSERT INTO l_zd_type VALUES ('ZAPM', 'ZONE ARRIERE DE POINT MUTUALISATION', '');
INSERT INTO l_zd_type VALUES ('ZAPBO', 'ZONE ARRIERE POINT DE BRANCHEMENT OPTIQUE', '');
INSERT INTO l_zd_type VALUES ('ZC', 'ZONE CABLO-OPERATEUR', '');
INSERT INTO l_zd_type VALUES ('ZA', 'ZONE AMENAGEMENT', '');
COMMIT;
